import type { AcpBehaviorReport, AcpBehaviorSnapshot } from './acp-behavior-probe.ts'

/**
 * Render {@link AcpBehaviorReport}s into Markdown + JSON for the Tier-2 ACP
 * behavioural probe. Pure functions of the reports — unit-tested without
 * spawning agents.
 */

const CELL = { yes: '✓', no: '·', unknown: '—' } as const

function routingLabel(routing: AcpBehaviorSnapshot['writeRouting']): string {
  switch (routing) {
    case 'fs_write_text_file':
      return 'fs/write'
    case 'shell_or_execute':
      return 'execute'
    case 'both':
      return 'both'
    case 'none':
      return CELL.no
  }
}

interface Row {
  label: string
  cell: (snapshot: AcpBehaviorSnapshot) => string
}

const ROWS: Row[] = [
  { label: 'Write routing', cell: (s) => routingLabel(s.writeRouting) },
  { label: 'fs/write_text_file calls', cell: (s) => String(s.fsWrites.length) },
  {
    label: 'execute tool calls',
    cell: (s) => String(s.toolCalls.filter((c) => c.kind === 'execute').length),
  },
  { label: 'Permission requests', cell: (s) => String(s.permissionRequests.length) },
  {
    label: 'Permission kinds',
    cell: (s): string => {
      const kinds = [...new Set(s.permissionRequests.map((p) => p.kind))]
      return kinds.length > 0 ? kinds.join(', ') : CELL.no
    },
  },
  {
    label: 'Mid-turn `_meta` keys',
    cell: (s) => (s.midTurnMetaKeys.length > 0 ? String(s.midTurnMetaKeys.length) : CELL.no),
  },
  {
    label: 'Update kinds',
    cell: (s) => (s.updateKinds.length > 0 ? String(s.updateKinds.length) : CELL.no),
  },
  { label: 'Stop reason', cell: (s) => s.stopReason ?? CELL.unknown },
]

function escapePipes(text: string): string {
  return text.replace(/\|/g, '\\|')
}

/** Render the Markdown behaviour matrix for a set of probe reports. */
export function renderBehaviorMatrixMarkdown(
  reports: readonly AcpBehaviorReport[],
  meta: { probedAt?: string; host?: string } = {},
): string {
  const lines: string[] = []
  lines.push('# ACP agent behaviour matrix')
  lines.push('')
  lines.push('> Generated by `npm run probe:acp:behavior` (Tier-2 behavioural probe). Each cell is')
  lines.push('> what the agent did under one real `session/prompt` — write routing, permission')
  lines.push(
    '> payloads, and mid-turn `_meta`. Spends model tokens; opt-in only. `—` means the agent failed to probe.',
  )
  lines.push('')
  if (meta.probedAt) lines.push(`- Probed at: ${meta.probedAt}`)
  if (meta.host) lines.push(`- Host: ${meta.host}`)
  lines.push('')

  if (reports.length === 0) {
    lines.push('_No agents were probed. Install an ACP agent (see `npm run detect:acp`) first._')
    lines.push('')
    return lines.join('\n')
  }

  const header = ['Observation', ...reports.map((r) => escapePipes(r.title))]
  lines.push(`| ${header.join(' | ')} |`)
  lines.push(`| ${header.map(() => '---').join(' | ')} |`)

  for (const row of ROWS) {
    const cells = reports.map((report) =>
      report.ok && report.snapshot ? escapePipes(row.cell(report.snapshot)) : CELL.unknown,
    )
    lines.push(`| ${[row.label, ...cells].join(' | ')} |`)
  }
  lines.push('')

  lines.push('## Details')
  lines.push('')
  for (const report of reports) {
    lines.push(`### ${report.title} (\`${report.agentId}\`)`)
    lines.push('')
    lines.push(`- Command: \`${[report.command, ...report.args].join(' ')}\``)
    if (!report.ok || !report.snapshot) {
      lines.push(`- **Probe failed:** ${report.error ?? 'unknown error'}`)
      lines.push('')
      continue
    }
    const s = report.snapshot
    lines.push(`- Write routing: \`${s.writeRouting}\``)
    if (s.fsWrites.length > 0) {
      lines.push(
        `- fs/write_text_file: ${s.fsWrites
          .map((w) => `\`${w.path}\` (${String(w.contentBytes)} bytes)`)
          .join(', ')}`,
      )
    }
    if (s.permissionRequests.length > 0) {
      for (const perm of s.permissionRequests) {
        lines.push(
          `- Permission: kind=\`${perm.kind}\` title=${JSON.stringify(perm.title ?? '')} ` +
            `options=[${perm.optionIds.join(', ')}] rawInputKeys=[${perm.rawInputKeys.join(', ')}]`,
        )
      }
    }
    if (s.toolCalls.length > 0) {
      lines.push(
        `- Tool calls: ${s.toolCalls
          .map((t) => `\`${t.kind}\` ${t.title ? JSON.stringify(t.title) : t.toolCallId}`)
          .join(', ')}`,
      )
    }
    if (s.updateKinds.length > 0) {
      lines.push(`- Update kinds: ${s.updateKinds.join(', ')}`)
    }
    if (s.midTurnMetaKeys.length > 0) {
      lines.push(
        `- Mid-turn \`_meta\` keys: ${s.midTurnMetaKeys.map((k) => `\`${k}\``).join(', ')}`,
      )
    }
    if (s.stopReason) {
      lines.push(`- Stop reason: \`${s.stopReason}\``)
    }
    lines.push('')
  }

  return lines.join('\n')
}

export interface AcpBehaviorMatrixJson {
  generatedBy: string
  probedAt?: string
  host?: string
  reports: readonly AcpBehaviorReport[]
}

export function buildBehaviorMatrixJson(
  reports: readonly AcpBehaviorReport[],
  meta: { probedAt?: string; host?: string } = {},
): AcpBehaviorMatrixJson {
  return {
    generatedBy: 'npm run probe:acp:behavior',
    ...(meta.probedAt ? { probedAt: meta.probedAt } : {}),
    ...(meta.host ? { host: meta.host } : {}),
    reports,
  }
}
