import assert from 'node:assert/strict'
import { afterEach, beforeEach, it } from 'node:test'
import { mkdirSync, mkdtempSync, realpathSync, rmSync, symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import {
  PREPARATION_CONFIG,
  PREPARATION_STAMP,
  formatPreparationApproval,
  readWorktreePreparationPlan,
} from './worktree-preparation-plan.ts'
import {
  inspectWorktreePreparation,
  resolveInstalledRustToolchainBin,
  selectInstalledRustupToolchainName,
} from './worktree-preparation.ts'

let root: string
beforeEach(() => {
  root = realpathSync(mkdtempSync(join(tmpdir(), 'cargo-preflight-')))
  write(
    'Cargo.toml',
    '[package]\nname = "app"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\ndep = "1.0.0"\n',
  )
  write('Cargo.lock', '# This file is automatically @generated by Cargo.\nversion = 4\n')
  write('crates/dep/Cargo.toml', '[package]\nname="dep"\nversion="0.1.0"\n')
})
afterEach(() => {
  rmSync(root, { recursive: true, force: true })
})

function write(path: string, text: string): void {
  const full = join(root, path)
  mkdirSync(join(full, '..'), { recursive: true })
  writeFileSync(full, text)
}

it('detects locked Cargo projects and describes fetch-only preparation', () => {
  const plan = readWorktreePreparationPlan(root)
  assert.equal(plan.ecosystem, 'cargo')
  assert.deepEqual(plan.problems, [])
  assert.deepEqual(plan.prepare, [
    {
      command: 'cargo',
      args: [
        'fetch',
        '--locked',
        '--manifest-path',
        'Cargo.toml',
        '--config',
        'net.git-fetch-with-cli=false',
      ],
    },
  ])
  assert.deepEqual(
    plan.checks.map(({ name, command }) => ({ name, command })),
    [
      { name: 'Cargo', command: { command: 'cargo', args: ['--version'] } },
      { name: 'Rust toolchain', command: { command: 'rustc', args: ['-vV'] } },
      {
        name: 'Locked Cargo dependencies',
        command: { command: 'cargo', args: [...(plan.prepare[0]?.args ?? []), '--offline'] },
      },
    ],
  )
  const approval = formatPreparationApproval(plan, false)
  assert.match(approval.body, /'cargo' 'fetch' '--locked'/)
  assert.match(approval.bodyAdvice, /dependency sources only/)
  assert.match(
    approval.bodyAdvice,
    /does not compile crates or run build scripts, tests, or binaries/,
  )
  assert.match(approval.bodyFooter, /project remains read-only/)
})

it('requires a lock, declarations for mixed roots, and fingerprints Cargo inputs', () => {
  rmSync(join(root, 'Cargo.lock'))
  assert.match(readWorktreePreparationPlan(root).problems.join(' '), /reviewed Cargo.lock/)
  write('Cargo.lock', 'version = 4\n')
  write('package.json', '{"packageManager":"npm@11.0.0"}')
  write('package-lock.json', '{}')
  assert.match(readWorktreePreparationPlan(root).problems.join(' '), /Multiple ecosystems/)
  write(PREPARATION_CONFIG, '{"version":1}')
  assert.equal(readWorktreePreparationPlan(root).ecosystem, null)
  rmSync(join(root, PREPARATION_CONFIG))
  rmSync(join(root, 'package.json'))
  rmSync(join(root, 'package-lock.json'))
  for (const [path, text] of [
    ['crates/dep/Cargo.toml', '[package]\nname="dep-two"\nversion="0.1.0"\n'],
    ['.cargo/config.toml', '[net]\nretry = 4\n'],
    ['rust-toolchain.toml', '[toolchain]\nchannel = "stable-aarch64-apple-darwin"\n'],
  ] satisfies Array<[string, string]>) {
    const before = readWorktreePreparationPlan(root).fingerprint
    write(path, text)
    assert.notEqual(readWorktreePreparationPlan(root).fingerprint, before)
  }
})

it('rejects executable Cargo config and local paths outside the worktree', () => {
  for (const config of [
    '[build]\nrustc-wrapper = "./wrapper"\n',
    '[registry]\nglobal-credential-providers = ["cargo:token"]\n',
    '[net]\ngit-fetch-with-cli = true\n',
    '[env]\nSECRET = "value"\n',
    'include = "../outside.toml"\n',
    'build.rustc-wrapper = "./wrapper"\n',
    '"rustc-wrapper" = "./wrapper"\n',
    'registries.private."credential-provider" = "cargo:token"\n',
  ]) {
    write('.cargo/config.toml', config)
    assert.match(
      readWorktreePreparationPlan(root).problems.join(' '),
      /declare Cargo setup explicitly/,
    )
  }
  rmSync(join(root, '.cargo/config.toml'))
  write('.cargo/config.toml', '[net]\nretry=2\n')
  write('nested/Cargo.toml', '[package]\nname="nested"\nversion="0.1.0"\n')
  write('nested/Cargo.lock', 'version=4\n')
  assert.match(
    readWorktreePreparationPlan(join(root, 'nested')).problems.join(' '),
    /configuration outside the selected project/,
  )
  rmSync(join(root, '.cargo/config.toml'))
  assert.match(
    readWorktreePreparationPlan(join(root, 'nested')).problems.join(' '),
    /enclosing Cargo.toml may select a workspace/,
  )
  for (const manifest of [
    '[package]\nname="app"\nversion="0.1.0"\n[dependencies]\nx={"path"="../outside"}\n',
    String.raw`[package]
name="app"
version="0.1.0"
[dependencies]
x={path="..\u002foutside"}
`,
    String.raw`[package]
name="app"
version="0.1.0"
[dependencies]
x={"pa\u0074h"="../outside"}
`,
    '[workspace]\n"members"=["../outside"]\n',
  ]) {
    write('Cargo.toml', manifest)
    assert.match(
      readWorktreePreparationPlan(root).problems.join(' '),
      /narrow unescaped registry\/Git manifest subset/,
    )
  }
  write(
    'Cargo.toml',
    '[package]\nname="app"\nversion="0.1.0"\n[dependencies]\nx={path="../outside"}\n',
  )
  assert.match(
    readWorktreePreparationPlan(root).problems.join(' '),
    /narrow unescaped registry\/Git manifest subset/,
  )

  const outside = realpathSync(mkdtempSync(join(tmpdir(), 'cargo-outside-')))
  try {
    write(
      'Cargo.toml',
      '[package]\nname="app"\nversion="0.1.0"\n[dependencies]\nx={path="linked"}\n',
    )
    symlinkSync(outside, join(root, 'linked'))
    assert.match(
      readWorktreePreparationPlan(root).problems.join(' '),
      /narrow unescaped registry\/Git manifest subset/,
    )
  } finally {
    rmSync(outside, { recursive: true, force: true })
  }
})

it('rejects untrusted toolchains and scrubs ambient Cargo and Rust controls', async () => {
  const toolchain = join(root, 'toolchain')
  write('toolchain/bin/cargo', 'cargo fixture')
  write('toolchain/bin/rustc', 'rustc fixture')
  assert.equal(resolveInstalledRustToolchainBin(root, { PATH: join(toolchain, 'bin') }), null)
  const outside = realpathSync(mkdtempSync(join(tmpdir(), 'cargo-toolchain-outside-')))
  writeFileSync(join(outside, 'rustc'), 'outside')
  rmSync(join(toolchain, 'bin', 'rustc'))
  symlinkSync(join(outside, 'rustc'), join(toolchain, 'bin', 'rustc'))
  assert.equal(resolveInstalledRustToolchainBin(root, { PATH: join(toolchain, 'bin') }), null)
  rmSync(join(toolchain, 'bin', 'rustc'))
  rmSync(outside, { recursive: true, force: true })
  write('toolchain/bin/rustc', 'rustc fixture')
  write('rust-toolchain', '')
  assert.equal(resolveInstalledRustToolchainBin(root, { PATH: '/usr/local/bin:/usr/bin' }), null)
  write('rust-toolchain', 'x'.repeat(64 * 1024 + 1))
  assert.equal(resolveInstalledRustToolchainBin(root, { PATH: '/usr/local/bin:/usr/bin' }), null)
  write('rust-toolchain', 'definitely-not-installed\n')
  assert.equal(
    resolveInstalledRustToolchainBin(root, {
      PATH: `/usr/local/bin:/usr/bin:${join(toolchain, 'bin')}`,
    }),
    null,
  )
  let hostileCalled = false
  const unavailable = await inspectWorktreePreparation(root, {
    env: {
      PATH: '/usr/local/bin:/usr/bin',
      CARGO: '/hostile/cargo',
      RUSTC: '/hostile/rustc',
    },
    probe: () => {
      hostileCalled = true
      return 'hostile'
    },
  })
  assert.equal(hostileCalled, false)
  assert.ok(unavailable.components.every((component) => !component.ready))
  rmSync(join(root, 'rust-toolchain'))
  const installed = resolveInstalledRustToolchainBin(root, process.env)
  assert.ok(installed, 'focused Cargo service test requires the installed Cargo used by CI')

  const seen: NodeJS.ProcessEnv[] = []
  const probe = (command: string, args: readonly string[], env: NodeJS.ProcessEnv): string => {
    seen.push(env)
    assert.equal(env['PATH'], installed)
    assert.equal(env['CARGO'], join(installed, 'cargo'))
    assert.equal(env['RUSTC'], join(installed, 'rustc'))
    assert.equal(env['CARGO_NET_OFFLINE'], 'true')
    assert.equal(env['CARGO_CACHE_AUTO_CLEAN_FREQUENCY'], 'never')
    assert.match(env['CARGO_HOME'] ?? '', /\/cargo$/)
    for (const key of ['RUSTC_WRAPPER', 'RUSTUP_HOME', 'RUSTFLAGS', 'CARGO_REGISTRY_TOKEN'])
      assert.equal(env[key], undefined)
    if (command === join(installed, 'cargo') && args[0] === '--version') return 'cargo 1.90.0'
    if (command === join(installed, 'rustc')) return 'rustc 1.90.0\nbinary: rustc'
    return ''
  }
  const env = {
    ...process.env,
    RUSTC_WRAPPER: '/outside/wrapper',
    RUSTUP_HOME: '/outside/rustup',
    RUSTFLAGS: '--cfg unsafe',
    CARGO_REGISTRY_TOKEN: 'secret',
    CARGO: '/outside/cargo',
    RUSTC: '/outside/rustc',
  }
  const first = await inspectWorktreePreparation(root, { env, probe })
  write(PREPARATION_STAMP, first.expectedFingerprint)
  assert.equal((await inspectWorktreePreparation(root, { env, probe })).state, 'ready')
  assert.ok(seen.length >= 6)
})

it('resolves an installed Rustup channel without relying on a default host setting', () => {
  assert.equal(
    selectInstalledRustupToolchainName('stable', 'stable-aarch64-unknown-linux-gnu', undefined, [
      'stable-aarch64-unknown-linux-gnu',
    ]),
    'stable-aarch64-unknown-linux-gnu',
  )
  assert.equal(
    selectInstalledRustupToolchainName('1.90', undefined, undefined, [
      '1.90-x86_64-unknown-linux-gnu',
    ]),
    '1.90-x86_64-unknown-linux-gnu',
  )
  assert.equal(
    selectInstalledRustupToolchainName('stable', undefined, undefined, [
      'stable-aarch64-apple-darwin',
      'stable-x86_64-unknown-linux-gnu',
    ]),
    null,
  )
})
