/**
 * The third-party licence report the build writes into the packaged app
 * (`dist/resources/licenses/third-party-licenses.json`, generated by
 * `scripts/lib/third-party-licenses.mts`) and Settings → About reads back.
 */
export const THIRD_PARTY_LICENSE_REPORT_VERSION = 1

/** Where the build writes the licence files, relative to the app root (unpacked from app.asar). */
export const THIRD_PARTY_LICENSES_DIR = 'dist/resources/licenses'
export const THIRD_PARTY_LICENSE_JSON = 'third-party-licenses.json'
export const THIRD_PARTY_LICENSE_TEXT = 'THIRD_PARTY_LICENSES.txt'
/**
 * Chromium's, Node's and their dependencies' notices, from Electron's dist/,
 * gzipped: the HTML is 20 MB and the app is near its size budget. Settings →
 * About decompresses it to a temporary file to open it.
 */
export const CHROMIUM_LICENSES_FILE = 'LICENSES.chromium.html.gz'
/** Copse's own licence. */
export const COPSE_LICENSE_FILE = 'LICENSE.txt'

/** The licence files Settings → About can open, by what they cover. */
export const LICENSE_FILE_KINDS = ['third-party', 'chromium', 'copse'] as const
export type LicenseFileKind = (typeof LICENSE_FILE_KINDS)[number]

/** What Settings → About shows. `report` is null in a dev build that never ran `pnpm build`. */
export interface AboutInfo {
  version: string
  report: ThirdPartyLicenseReport | null
}

/**
 * How a component reaches the packaged app. `bundled`: compiled into a
 * `dist/**.js` bundle by esbuild. `node_modules`: copied into app.asar by
 * electron-builder. `copied`: files copied out of a package by the build (the
 * Monaco `vs/` tree, the material icons). `vendored`: checked into this
 * repository or fetched at install time (fonts, gortex, the Electron runtime).
 */
export const THIRD_PARTY_SHIPPED_AS = ['bundled', 'copied', 'node_modules', 'vendored'] as const
export type ThirdPartyShippedAs = (typeof THIRD_PARTY_SHIPPED_AS)[number]

export interface ThirdPartyComponent {
  name: string
  version: string
  /** The declared SPDX expression, as the component states it. */
  license: string
  source: string | null
  shippedAs: ThirdPartyShippedAs[]
  /** The shipped component this one is compiled into (a Go module inside gortex), if any. */
  partOf: string | null
  /** Why the component has no licence file, or where its text came from. */
  note?: string | undefined
  /** Each licence/notice file, with its text as an index into the report's `texts`. */
  files: { name: string; text: number }[]
}

export interface ThirdPartyLicenseReport {
  version: typeof THIRD_PARTY_LICENSE_REPORT_VERSION
  components: ThirdPartyComponent[]
  /** Licence texts, deduplicated: many components share a byte-identical file. */
  texts: string[]
}
