// Generated by `npm run demo:trace` from a thread JSONL export — do not edit by hand.
import type { DemoTrace } from '../demo-traces.ts'

export const LANDING_TRACE: DemoTrace = {
  id: 'landing',
  label: 'Landing hero',
  prompt: 'how does the demo preview comment know which scenarios to link?',
  steps: [
    {
      chunk: {
        type: 'reasoning',
        text: 'The comment is written by a workflow, so the scenario list is either hard-coded there or handed to it by the build. Start at the workflow and follow the value backwards.',
      },
    },
    {
      chunk: {
        type: 'text',
        text: 'The comment is generated in CI, so the list is either hard-coded in the workflow or emitted by the build. Following it back from the comment step:',
      },
    },
    {
      chunk: {
        type: 'tool_call',
        toolCall: {
          id: 'tc-1',
          name: 'search_code',
          args: {
            pattern: 'scenarios',
            path: '.github/workflows/demo-preview.yml',
          },
        },
      },
      delayMs: 420,
    },
    {
      chunk: {
        type: 'tool_result',
        toolCallId: 'tc-1',
        result:
          ".github/workflows/demo-preview.yml:46:scenarios: ${{ steps.scenarios.outputs.json }}\n.github/workflows/demo-preview.yml:83:- id: scenarios\n.github/workflows/demo-preview.yml:88:tr -d '\\n' < dist/demo/scenarios.json 2>/dev/null || echo '[]'\n.github/workflows/demo-preview.yml:152:SCENARIOS: ${{ needs.publish.outputs.scenarios }}\n.github/workflows/demo-preview.yml:164:let scenarios = [];\n.github/workflows/demo-preview.yml:166:scenarios = JSON.parse(process.env.SCENARIOS || '[]');\n.github/workflows/demo-preview.yml:168:scenarios = [];\n.github/workflows/demo-preview.yml:170:const links = scenarios",
        isError: false,
      },
      delayMs: 900,
    },
    {
      chunk: {
        type: 'tool_call',
        toolCall: {
          id: 'tc-2',
          name: 'read_file',
          args: {
            path: 'scripts/build.mts',
            start_line: 27,
            end_line: 47,
          },
        },
      },
      delayMs: 420,
    },
    {
      chunk: {
        type: 'tool_result',
        toolCallId: 'tc-2',
        result:
          "// Emit a scenario manifest (id + label) alongside the demo build so the per-PR\n// demo-preview PR comment can link each selectable `?scenario=` state without\n// hard-coding the list. `demo-scenarios.ts` has only a type-only import, so\n// esbuild bundles it standalone; we import the emitted module and read the\n// exported list back. Best-effort: any failure writes `[]` rather than breaking\n// the demo build, since the comment degrades gracefully without it.\nasync function writeDemoScenarioManifest(outPath: string): Promise<void> {\n  const tempModule = resolve('dist', '.demo-scenarios.mjs')\n  try {\n    await esbuild.build({\n      entryPoints: ['src/shared/demo-scenarios.ts'],\n      bundle: true,\n      platform: 'node',\n      format: 'esm',\n      outfile: tempModule,\n      alias: sharedAlias,\n    })\n    const imported: unknown = await import(pathToFileURL(tempModule).href)\n    const list =\n      imported !== null && typeof imported === 'object' && 'DEMO_SCENARIOS' in imported\n        ? imported.DEMO_SCENARIOS",
        isError: false,
      },
      delayMs: 900,
    },
    {
      chunk: {
        type: 'tool_call',
        toolCall: {
          id: 'tc-3',
          name: 'read_file',
          args: {
            path: 'src/shared/demo-scenarios.ts',
            start_line: 1,
            end_line: 16,
          },
        },
      },
      delayMs: 420,
    },
    {
      chunk: {
        type: 'tool_result',
        toolCallId: 'tc-3',
        result:
          "import type { Project, Thread } from './types/index.ts'\nimport type { DemoTrace } from './demo-traces.ts'\nimport { LANDING_TRACE } from './demo-traces/landing.ts'\n\nconst FIXED_TIME = Date.UTC(2026, 6, 17, 9, 0, 0)\nconst FOOTER_INPUT_TOKENS = 50_000\nconst FOOTER_OUTPUT_TOKENS = 1_800\n\nexport interface DemoScenario {\n  id: string\n  label: string\n  project: Project\n  threads: Thread[]\n  settings: Readonly<Record<string, unknown>>\n  /**\n   * A recorded turn the demo can replay when its prompt is submitted. Scenarios",
        isError: false,
      },
      delayMs: 900,
    },
    {
      chunk: {
        type: 'text',
        text: "Nothing hard-codes it — the list is a build output.\n\n### The chain\n\n1. **`src/shared/demo-scenarios.ts`** is the single source: `DEMO_SCENARIOS` holds every\n   `{ id, label, project, threads, settings }` the demo can boot into.\n2. **`scripts/build.mts`** (`writeDemoScenarioManifest`) bundles that module on its own with\n   esbuild, imports the result, and writes `id` + `label` pairs to `dist/demo/scenarios.json`.\n3. **`.github/workflows/demo-preview.yml`** reads that file into a step output:\n\n   ```yaml\n   tr -d '\\n' < dist/demo/scenarios.json 2>/dev/null || echo '[]'\n   ```\n\n4. The `comment` job parses it and maps each entry to `?scenario=<id>`.\n\n### What that means for you\n\nAdd a scenario to `DEMO_SCENARIOS` and the PR comment picks it up on the next push — no\nworkflow edit. The manifest step is deliberately best-effort: if the bundle fails it writes\n`[]` and the comment degrades to a bare preview link rather than failing the build.",
      },
    },
    {
      chunk: {
        type: 'usage',
        model: 'claude-sonnet-5',
        inputTokens: 41820,
        outputTokens: 1264,
        cacheReadTokens: 38400,
      },
      delayMs: 300,
    },
    {
      chunk: {
        type: 'done',
        stopReason: 'end_turn',
      },
      delayMs: 300,
    },
  ],
  source: {
    exportVersion: 5,
    threadId: 'a2f1c6d4-9f4a-4a91-8d7e-3f0b1c2d4e5f',
    title: 'Where the demo scenario list comes from',
    turn: 0,
    model: 'claude-sonnet-5',
  },
}
