import { describe, it, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { stripSyncDate, formatGenerated, writeGeneratedFile } from './generated-file.mts'

let root = ''
before(() => {
  root = mkdtempSync(join(tmpdir(), 'copse-generated-file-'))
})
after(() => {
  rmSync(root, { recursive: true, force: true })
})

/** What a generator's `renderFile` emits: a stamped header + one-line literals. */
function render(date: string, value: number): string {
  return `// AUTO-GENERATED by scripts/sync-fake.mts. Do not edit by hand.
// Last synced: ${date}

export const SCORES: Record<string, { value: number; source: string; asOf: string }> = {
  'some/model-with-a-fairly-long-id': { value: ${String(value)}, source: 'A source string long enough to push this literal past printWidth', asOf: '2026-01-01' },
}
`
}

describe('stripSyncDate', () => {
  it('removes the header line and leaves everything else', () => {
    assert.equal(
      stripSyncDate('// head\n// Last synced: 2026-08-08\n\nconst a = 1\n'),
      '// head\n\nconst a = 1\n',
    )
  })

  it('leaves a file without the header untouched', () => {
    assert.equal(stripSyncDate('const a = 1\n'), 'const a = 1\n')
  })
})

describe('writeGeneratedFile', () => {
  it('writes when the file does not exist yet', async () => {
    const path = join(root, 'new.generated.ts')
    assert.equal(await writeGeneratedFile(path, render('2026-08-08', 55)), true)
    assert.match(readFileSync(path, 'utf8'), /Last synced: 2026-08-08/)
  })

  it('leaves a prettier-formatted file alone when only the date moved', async () => {
    // The regression this module exists for. The file on disk is what prettier
    // left behind (multi-line literals); `content` is the raw render (one-line).
    // Comparing those two directly never matched, so every run rewrote the file
    // and churned a one-line `Last synced:` diff on identical data.
    const path = join(root, 'quiet.generated.ts')
    writeFileSync(path, await formatGenerated(path, render('2026-08-07', 55)), 'utf8')
    const before = readFileSync(path, 'utf8')

    assert.equal(await writeGeneratedFile(path, render('2026-08-08', 55)), false)
    assert.equal(readFileSync(path, 'utf8'), before)
    assert.match(before, /Last synced: 2026-08-07/)
  })

  it('writes when a value actually moved, stamping the new date', async () => {
    const path = join(root, 'moved.generated.ts')
    writeFileSync(path, await formatGenerated(path, render('2026-08-07', 55)), 'utf8')

    assert.equal(await writeGeneratedFile(path, render('2026-08-08', 61)), true)
    const after = readFileSync(path, 'utf8')
    assert.match(after, /Last synced: 2026-08-08/)
    assert.match(after, /value: 61/)
  })

  it('leaves the file prettier-clean, so the next run compares like for like', async () => {
    const path = join(root, 'formatted.generated.ts')
    await writeGeneratedFile(path, render('2026-08-08', 55))
    const written = readFileSync(path, 'utf8')

    // Written through prettier: the long literal is exploded, not left as rendered.
    assert.match(written, /\n {4}value: 55,\n/)
    assert.equal(written, await formatGenerated(path, written))
    // And a same-day re-run of the identical render is a no-op, not a rewrite.
    assert.equal(await writeGeneratedFile(path, render('2026-08-09', 55)), false)
  })
})
