// AUTO-GENERATED by scripts/sync-intellect.mts. Do not edit by hand.
// Intelligence-index measurements (cloud + local model ids) and crystallised
// cross-version equating maps. Source of truth: scripts/data/intellect-scores.json.
// Absent models mean "no sourced measurement yet", not zero.
// Intelligence Index data from Artificial Analysis (https://artificialanalysis.ai)
// Last synced: 2026-07-18

import type { EquatingMap } from './intellect-equating.ts'

export interface IntellectMeasurement {
  value: number
  indexVersion: string
  source: string
  asOf: string
}

/** The permanent display/comparison scale. Changing it is a breaking re-baseline. */
export const CANONICAL_INTELLECT_VERSION = 'v4.1'

export const INTELLECT_ATTRIBUTION =
  'Intelligence Index data from Artificial Analysis (https://artificialanalysis.ai)'

export const MODEL_INTELLECT_RAW: Record<string, IntellectMeasurement[]> = {
  'claude-opus-4-8': [
    {
      value: 56,
      indexVersion: 'v4.1',
      source:
        'Artificial Analysis Intelligence Index v4.1 chart (@ArtificialAnlys), via Latent Space AINews Kimi K3 coverage: Fable 5 = 60, GPT-5.6 = 59, Kimi K3 = 57, Opus 4.8 = 56',
      asOf: '2026-07-16',
    },
  ],
  'claude-sonnet-4-6': [
    {
      value: 47,
      indexVersion: 'v4.1',
      source:
        "Derived by stated difference from @ArtificialAnlys: 'Claude Sonnet 5 achieves 53 on the Artificial Analysis Intelligence Index … with max effort it improves 6 points over Sonnet 4.6' → 53 − 6 = 47",
      asOf: '2026-07-02',
    },
  ],
}

export const INTELLECT_EQUATING_MAPS: readonly EquatingMap[] = []
