// AUTO-GENERATED by scripts/sync-model-catalog.mts. Do not edit by hand.
// Source: https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
// Last synced: 2026-09-20

export interface CatalogEntry {
  inputPricePerMTok: number
  outputPricePerMTok: number
  cacheReadPricePerMTok?: number
  cacheCreationPricePerMTok?: number
  serviceTierPricing?: Partial<
    Record<
      'flex' | 'priority',
      {
        inputPricePerMTok: number
        outputPricePerMTok: number
        cacheReadPricePerMTok?: number
        cacheCreationPricePerMTok?: number
      }
    >
  >
  contextWindow: number
  maxOutputTokens: number
}

export const MODEL_CATALOG: Record<string, CatalogEntry> = {
  'claude-fable-5': {
    inputPricePerMTok: 10,
    outputPricePerMTok: 50,
    cacheReadPricePerMTok: 1,
    cacheCreationPricePerMTok: 12.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-fable-5-1': {
    inputPricePerMTok: 10,
    outputPricePerMTok: 50,
    cacheReadPricePerMTok: 0.25,
    cacheCreationPricePerMTok: 12.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-haiku-4-5': {
    inputPricePerMTok: 1,
    outputPricePerMTok: 5,
    cacheReadPricePerMTok: 0.1,
    cacheCreationPricePerMTok: 1.25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
  },
  'claude-opus-4-8': {
    inputPricePerMTok: 5,
    outputPricePerMTok: 25,
    cacheReadPricePerMTok: 0.5,
    cacheCreationPricePerMTok: 6.25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-opus-5': {
    inputPricePerMTok: 5,
    outputPricePerMTok: 25,
    cacheReadPricePerMTok: 0.5,
    cacheCreationPricePerMTok: 6.25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-sonnet-4-6': {
    inputPricePerMTok: 3,
    outputPricePerMTok: 15,
    cacheReadPricePerMTok: 0.3,
    cacheCreationPricePerMTok: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-sonnet-5': {
    inputPricePerMTok: 2,
    outputPricePerMTok: 10,
    cacheReadPricePerMTok: 0.2,
    cacheCreationPricePerMTok: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'gpt-4o': {
    inputPricePerMTok: 2.5,
    outputPricePerMTok: 10,
    cacheReadPricePerMTok: 1.25,
    serviceTierPricing: {
      priority: { inputPricePerMTok: 4.25, outputPricePerMTok: 17, cacheReadPricePerMTok: 2.125 },
    },
    contextWindow: 128000,
    maxOutputTokens: 16384,
  },
  'gpt-4o-mini': {
    inputPricePerMTok: 0.15,
    outputPricePerMTok: 0.6,
    cacheReadPricePerMTok: 0.075,
    serviceTierPricing: {
      priority: { inputPricePerMTok: 0.25, outputPricePerMTok: 1, cacheReadPricePerMTok: 0.125 },
    },
    contextWindow: 128000,
    maxOutputTokens: 16384,
  },
  'gpt-5': {
    inputPricePerMTok: 1.25,
    outputPricePerMTok: 10,
    cacheReadPricePerMTok: 0.125,
    serviceTierPricing: {
      flex: { inputPricePerMTok: 0.625, outputPricePerMTok: 5, cacheReadPricePerMTok: 0.0625 },
      priority: { inputPricePerMTok: 2.5, outputPricePerMTok: 20, cacheReadPricePerMTok: 0.25 },
    },
    contextWindow: 272000,
    maxOutputTokens: 128000,
  },
  'gpt-5-mini': {
    inputPricePerMTok: 0.25,
    outputPricePerMTok: 2,
    cacheReadPricePerMTok: 0.025,
    serviceTierPricing: {
      flex: { inputPricePerMTok: 0.125, outputPricePerMTok: 1, cacheReadPricePerMTok: 0.0125 },
      priority: { inputPricePerMTok: 0.45, outputPricePerMTok: 3.6, cacheReadPricePerMTok: 0.045 },
    },
    contextWindow: 272000,
    maxOutputTokens: 128000,
  },
  'gpt-5-nano': {
    inputPricePerMTok: 0.05,
    outputPricePerMTok: 0.4,
    cacheReadPricePerMTok: 0.005,
    serviceTierPricing: {
      flex: { inputPricePerMTok: 0.025, outputPricePerMTok: 0.2, cacheReadPricePerMTok: 0.0025 },
    },
    contextWindow: 272000,
    maxOutputTokens: 128000,
  },
  'gpt-5.5': {
    inputPricePerMTok: 5,
    outputPricePerMTok: 30,
    cacheReadPricePerMTok: 0.5,
    serviceTierPricing: {
      flex: { inputPricePerMTok: 2.5, outputPricePerMTok: 15, cacheReadPricePerMTok: 0.25 },
      priority: { inputPricePerMTok: 12.5, outputPricePerMTok: 75, cacheReadPricePerMTok: 1.25 },
    },
    contextWindow: 1050000,
    maxOutputTokens: 128000,
  },
  'gpt-5.6-luna': {
    inputPricePerMTok: 0.2,
    outputPricePerMTok: 1.2,
    cacheReadPricePerMTok: 0.02,
    cacheCreationPricePerMTok: 0.25,
    serviceTierPricing: {
      flex: {
        inputPricePerMTok: 0.1,
        outputPricePerMTok: 0.6,
        cacheReadPricePerMTok: 0.01,
        cacheCreationPricePerMTok: 0.125,
      },
      priority: {
        inputPricePerMTok: 0.4,
        outputPricePerMTok: 2.4,
        cacheReadPricePerMTok: 0.04,
        cacheCreationPricePerMTok: 0.5,
      },
    },
    contextWindow: 922000,
    maxOutputTokens: 128000,
  },
  'gpt-5.6-sol': {
    inputPricePerMTok: 4,
    outputPricePerMTok: 20,
    cacheReadPricePerMTok: 0.4,
    cacheCreationPricePerMTok: 5,
    serviceTierPricing: {
      flex: {
        inputPricePerMTok: 2,
        outputPricePerMTok: 10,
        cacheReadPricePerMTok: 0.2,
        cacheCreationPricePerMTok: 2.5,
      },
      priority: {
        inputPricePerMTok: 8,
        outputPricePerMTok: 40,
        cacheReadPricePerMTok: 0.8,
        cacheCreationPricePerMTok: 10,
      },
    },
    contextWindow: 922000,
    maxOutputTokens: 128000,
  },
  'gpt-5.6-terra': {
    inputPricePerMTok: 2,
    outputPricePerMTok: 12,
    cacheReadPricePerMTok: 0.2,
    cacheCreationPricePerMTok: 2.5,
    serviceTierPricing: {
      flex: {
        inputPricePerMTok: 1,
        outputPricePerMTok: 6,
        cacheReadPricePerMTok: 0.1,
        cacheCreationPricePerMTok: 1.25,
      },
      priority: {
        inputPricePerMTok: 4,
        outputPricePerMTok: 24,
        cacheReadPricePerMTok: 0.4,
        cacheCreationPricePerMTok: 5,
      },
    },
    contextWindow: 922000,
    maxOutputTokens: 128000,
  },
  'gpt-6-astra': {
    inputPricePerMTok: 10,
    outputPricePerMTok: 50,
    cacheReadPricePerMTok: 1,
    cacheCreationPricePerMTok: 12.5,
    serviceTierPricing: {
      flex: {
        inputPricePerMTok: 5,
        outputPricePerMTok: 25,
        cacheReadPricePerMTok: 0.5,
        cacheCreationPricePerMTok: 6.25,
      },
      priority: {
        inputPricePerMTok: 20,
        outputPricePerMTok: 100,
        cacheReadPricePerMTok: 2,
        cacheCreationPricePerMTok: 25,
      },
    },
    contextWindow: 922000,
    maxOutputTokens: 128000,
  },
}
