// AUTO-GENERATED by scripts/sync-intellect.mts. Do not edit by hand.
// Intelligence-index measurements (cloud + local model ids) and crystallised
// cross-version equating maps. Source of truth: scripts/data/intellect-scores.json.
// Absent models mean "no sourced measurement yet", not zero.
// Intelligence Index data from Artificial Analysis (https://artificialanalysis.ai)
// Last synced: 2026-07-21

import type { EquatingMap } from './intellect-equating.ts'

export interface IntellectMeasurement {
  value: number
  indexVersion: string
  source: string
  asOf: string
}

/** The permanent display/comparison scale. Changing it is a breaking re-baseline. */
export const CANONICAL_INTELLECT_VERSION = 'v4.1'

export const INTELLECT_ATTRIBUTION =
  'Intelligence Index data from Artificial Analysis (https://artificialanalysis.ai)'

export const MODEL_INTELLECT_RAW: Record<string, IntellectMeasurement[]> = {
  'MiniMaxAI/MiniMax-M3': [
    {
      value: 55,
      indexVersion: 'v4.0',
      source:
        "@ArtificialAnlys: 'MiniMax-M3 scores 55 on the Artificial Analysis Intelligence Index' (June 2026 index cohort, Opus 4.8 = 61), https://artificialanalysis.ai/articles/minimax-m3",
      asOf: '2026-06-18',
    },
    {
      value: 44.4,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'minimax-m3', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'claude-fable-5': [
    {
      value: 59.9,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'claude-fable-5', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'claude-haiku-4-5': [
    {
      value: 24,
      indexVersion: 'v4.1',
      source:
        'Artificial Analysis model page for Claude 4.5 Haiku (non-reasoning variant), https://artificialanalysis.ai/models/claude-4-5-haiku, retrieved 2026-07-18',
      asOf: '2026-07-18',
    },
  ],
  'claude-opus-4-8': [
    {
      value: 61,
      indexVersion: 'v4.0',
      source:
        "Artificial Analysis MiniMax-M3 coverage (June 2026 index cohort): 'Claude Opus 4.8 currently leads the index at 61, followed by GPT-5.5 at 60', https://artificialanalysis.ai/articles/minimax-m3",
      asOf: '2026-06-18',
    },
    {
      value: 55.7,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'claude-opus-4-8', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'claude-sonnet-4-6': [
    {
      value: 35.9,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'claude-sonnet-4-6', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'claude-sonnet-5': [
    {
      value: 53.4,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'claude-sonnet-5', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'deepseek/deepseek-coder-v2-lite': [
    {
      value: 3.1,
      indexVersion: 'v4.1',
      source:
        "Artificial Analysis API (index v4.1), model 'deepseek-coder-v2-lite', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'google/gemma-3-12b': [
    {
      value: 5.5,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gemma-3-12b', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'google/gemma-4-e4b': [
    {
      value: 12.5,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gemma-4-e4b', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'gpt-4o': [
    {
      value: 11.2,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gpt-4o', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'gpt-4o-mini': [
    {
      value: 6.9,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gpt-4o-mini', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'gpt-5': [
    {
      value: 34.7,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gpt-5', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'gpt-5-mini': [
    {
      value: 25.3,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'gpt-5-mini', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'gpt-5.5': [
    {
      value: 60,
      indexVersion: 'v4.0',
      source:
        "Artificial Analysis MiniMax-M3 coverage (June 2026 index cohort): 'Claude Opus 4.8 currently leads the index at 61, followed by GPT-5.5 at 60', https://artificialanalysis.ai/articles/minimax-m3",
      asOf: '2026-06-18',
    },
    {
      value: 55,
      indexVersion: 'v4.1',
      source:
        'Artificial Analysis Intelligence Index v4.1 (July 2026 leaderboard): Fable 5 = 60, GPT-5.6 Sol = 59, Opus 4.8 = 56, GPT-5.5 = 55; see https://artificialanalysis.ai/articles/artificial-analysis-intelligence-index-v4-1',
      asOf: '2026-07-18',
    },
  ],
  'gpt-5.6-sol': [
    {
      value: 59,
      indexVersion: 'v4.1',
      source:
        "Artificial Analysis Intelligence Index v4.1 chart (@ArtificialAnlys), chart label 'GPT-5.6' (AA's frontier GPT-5.6 Sol entry), via Latent Space AINews Kimi K3 coverage, 2026-07-16",
      asOf: '2026-07-16',
    },
  ],
  'gpt-5.6-terra': [
    {
      value: 46,
      indexVersion: 'v4.1',
      source:
        "Artificial Analysis comparison page: 'GPT-5.6 Terra (medium) scores 46 on the Artificial Analysis Intelligence Index', https://artificialanalysis.ai/models/comparisons/gpt-5-6-terra-medium-vs-claude-sonnet-5, retrieved 2026-07-18",
      asOf: '2026-07-18',
    },
  ],
  'grok-4.5': [
    {
      value: 53.8,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'grok-4-5', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'microsoft/phi-4': [
    {
      value: 4.9,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'phi-4', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'mistralai/mistral-small-24b': [
    {
      value: 14.7,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'mistral-small-3-1', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'moonshotai/kimi-k2.6': [
    {
      value: 54,
      indexVersion: 'v4.0',
      source:
        "Artificial Analysis MiniMax-M3 coverage (June 2026 index cohort): M3 at 55 'edging ahead of Kimi K2.6 and MiMo-V2.5-Pro, both sitting at 54', https://artificialanalysis.ai/articles/minimax-m3",
      asOf: '2026-06-18',
    },
    {
      value: 44.2,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'kimi-k2-6', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'moonshotai/kimi-k3': [
    {
      value: 57.1,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'kimi-k3', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'qwen/qwen2.5-coder-32b': [
    {
      value: 7.1,
      indexVersion: 'v4.1',
      source:
        "Artificial Analysis API (index v4.1), model 'qwen2-5-coder-32b-instruct', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'qwen/qwen3.6-35b-a3b': [
    {
      value: 31.6,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'qwen3-6-35b-a3b', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
  'zai-org/GLM-5.2': [
    {
      value: 51.1,
      indexVersion: 'v4.1',
      source: "Artificial Analysis API (index v4.1), model 'glm-5-2', fetched 2026-07-19",
      asOf: '2026-07-19',
    },
  ],
}

/** Alternate id/label forms (OpenRouter ids, ACP labels) → catalog model id. */
export const INTELLECT_ALIASES: Record<string, string> = {
  'anthropic/claude-fable-5': 'claude-fable-5',
  'anthropic/claude-haiku-4-5': 'claude-haiku-4-5',
  'anthropic/claude-opus-4-8': 'claude-opus-4-8',
  'anthropic/claude-sonnet-4-6': 'claude-sonnet-4-6',
  'anthropic/claude-sonnet-5': 'claude-sonnet-5',
  'Claude Fable 5': 'claude-fable-5',
  'Claude Sonnet 5': 'claude-sonnet-5',
  'claude-fable-5-latest': 'claude-fable-5',
  'claude-haiku-4-5-latest': 'claude-haiku-4-5',
  'claude-opus-4-8-latest': 'claude-opus-4-8',
  'claude-sonnet-4-6-latest': 'claude-sonnet-4-6',
  'claude-sonnet-5-latest': 'claude-sonnet-5',
  'Cursor Grok 4.5': 'grok-4.5',
  'DeepSeek-Coder V2 Lite': 'deepseek/deepseek-coder-v2-lite',
  'deepseek-coder-v2-lite': 'deepseek/deepseek-coder-v2-lite',
  'deepseek-coder-v2-lite-instruct': 'deepseek/deepseek-coder-v2-lite',
  'Fable 5': 'claude-fable-5',
  'Gemma 3 12B': 'google/gemma-3-12b',
  'Gemma 4 E4B': 'google/gemma-4-e4b',
  'gemma-3-12b': 'google/gemma-3-12b',
  'gemma-3-12b-it': 'google/gemma-3-12b',
  'gemma-4-e4b': 'google/gemma-4-e4b',
  'gemma-4-e4b-it': 'google/gemma-4-e4b',
  'glm-5-2': 'zai-org/GLM-5.2',
  'glm-5.2': 'zai-org/GLM-5.2',
  'GLM-5.2': 'zai-org/GLM-5.2',
  'GPT-5.5': 'gpt-5.5',
  'GPT-5.6 Sol': 'gpt-5.6-sol',
  'GPT-5.6 Terra': 'gpt-5.6-terra',
  'GPT-5.6-Terra': 'gpt-5.6-terra',
  'Grok 4.5': 'grok-4.5',
  'grok-4-5': 'grok-4.5',
  'grok-build-0.1': 'grok-4.5',
  'Haiku 4.5': 'claude-haiku-4-5',
  'Kimi K2.6': 'moonshotai/kimi-k2.6',
  'Kimi K3': 'moonshotai/kimi-k3',
  'kimi-k2.6': 'moonshotai/kimi-k2.6',
  'kimi-k3': 'moonshotai/kimi-k3',
  'minimax-m3': 'MiniMaxAI/MiniMax-M3',
  'MiniMax-M3': 'MiniMaxAI/MiniMax-M3',
  'minimax/minimax-m3': 'MiniMaxAI/MiniMax-M3',
  'Mistral Small 24B': 'mistralai/mistral-small-24b',
  'mistral-small-24b': 'mistralai/mistral-small-24b',
  'mistral-small-3': 'mistralai/mistral-small-24b',
  'mistral-small-3-1': 'mistralai/mistral-small-24b',
  'moonshot/kimi-k2.6': 'moonshotai/kimi-k2.6',
  'moonshot/kimi-k3': 'moonshotai/kimi-k3',
  'moonshotai/kimi-k2-6': 'moonshotai/kimi-k2.6',
  'openai/gpt-4o': 'gpt-4o',
  'openai/gpt-4o-mini': 'gpt-4o-mini',
  'openai/gpt-5': 'gpt-5',
  'openai/gpt-5-mini': 'gpt-5-mini',
  'openai/gpt-5.5': 'gpt-5.5',
  'openai/gpt-5.6-sol': 'gpt-5.6-sol',
  'openai/gpt-5.6-terra': 'gpt-5.6-terra',
  'Opus 4.8': 'claude-opus-4-8',
  'phi-4': 'microsoft/phi-4',
  'Phi-4': 'microsoft/phi-4',
  'qwen2-5-coder-32b-instruct': 'qwen/qwen2.5-coder-32b',
  'Qwen2.5-Coder 32B': 'qwen/qwen2.5-coder-32b',
  'qwen2.5-coder-32b-instruct': 'qwen/qwen2.5-coder-32b',
  'qwen3-6-35b-a3b': 'qwen/qwen3.6-35b-a3b',
  'Qwen3.6 35B A3B': 'qwen/qwen3.6-35b-a3b',
  'qwen3.6-35b-a3b': 'qwen/qwen3.6-35b-a3b',
  'Sonnet 4.6': 'claude-sonnet-4-6',
  'Sonnet 5': 'claude-sonnet-5',
  'x-ai/grok-4.5': 'grok-4.5',
  'xai/grok-4.5': 'grok-4.5',
  'z-ai/glm-5.2': 'zai-org/GLM-5.2',
  'zai/glm-5.2': 'zai-org/GLM-5.2',
}

export const INTELLECT_EQUATING_MAPS: readonly EquatingMap[] = [
  {
    from: 'v4.0',
    to: 'v4.1',
    a: 1,
    b: -5,
    anchorCount: 2,
    anchorMin: 60,
    anchorMax: 61,
    fittedAsOf: '2026-07-18',
  },
]
