// AUTO-GENERATED by scripts/sync-model-cards.mts. Do not edit by hand.
// Vendor-published model cards / system cards, keyed by canonical model id.
// Source of truth: scripts/data/model-cards.json.
// Absent models mean "no sourced card yet", and the UI shows no link.
// Last synced: 2026-09-04

/** Whether a link is a card about this model, or a vendor hub listing cards. */
export type ModelCardKind = 'system-card' | 'model-card' | 'index'

export interface ModelCard {
  /** The vendor's own published page or PDF. */
  url: string
  /** Human title for the link. */
  title: string
  /** Who published it, e.g. "Anthropic". */
  publisher: string
  kind: ModelCardKind
  /**
   * ISO date the link was last reviewed. Absent on a card derived at lookup
   * time from the model id itself (see `huggingFaceCardUrl`), which is as
   * current as the id is.
   */
  asOf?: string
}

export const MODEL_CARDS: Record<string, ModelCard> = {
  'claude-fable-5': {
    url: 'https://www.anthropic.com/claude-fable-5-mythos-5-system-card',
    title: 'Claude Fable 5 & Claude Mythos 5 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-fable-5-1': {
    url: 'https://www.anthropic.com/claude-fable-5-1-mythos-5-1-system-card',
    title: 'Claude Fable 5.1 & Claude Mythos 5.1 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-haiku-4-5': {
    url: 'https://www.anthropic.com/claude-haiku-4-5-system-card',
    title: 'Claude Haiku 4.5 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-opus-4-8': {
    url: 'https://www.anthropic.com/claude-opus-4-8-system-card',
    title: 'Claude Opus 4.8 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-opus-5': {
    url: 'https://www.anthropic.com/claude-opus-5-system-card',
    title: 'Claude Opus 5 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-sonnet-4-6': {
    url: 'https://www.anthropic.com/claude-sonnet-4-6-system-card',
    title: 'Claude Sonnet 4.6 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'claude-sonnet-5': {
    url: 'https://www.anthropic.com/claude-sonnet-5-system-card',
    title: 'Claude Sonnet 5 system card',
    publisher: 'Anthropic',
    kind: 'system-card',
    asOf: '2026-09-02',
  },
  'gemini-2-0-flash': {
    url: 'https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-2-0-Flash-Model-Card.pdf',
    title: 'Gemini 2.0 Flash model card',
    publisher: 'Google DeepMind',
    kind: 'model-card',
    asOf: '2026-09-04',
  },
  'gemini-2-0-flash-lite-001': {
    url: 'https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-2-0-Flash-Lite-Model-Card.pdf',
    title: 'Gemini 2.0 Flash-Lite model card',
    publisher: 'Google DeepMind',
    kind: 'model-card',
    asOf: '2026-09-04',
  },
  'gemini-2-5-flash': {
    url: 'https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-2-5-Flash-Model-Card.pdf',
    title: 'Gemini 2.5 Flash model card',
    publisher: 'Google DeepMind',
    kind: 'model-card',
    asOf: '2026-09-04',
  },
  'gemini-2-5-flash-lite': {
    url: 'https://storage.googleapis.com/deepmind-media/Model-Cards/Gemini-2-5-Flash-Lite-Model-Card.pdf',
    title: 'Gemini 2.5 Flash-Lite model card',
    publisher: 'Google DeepMind',
    kind: 'model-card',
    asOf: '2026-09-04',
  },
  'gpt-4o': {
    url: 'https://openai.com/index/gpt-4o-system-card/',
    title: 'GPT-4o system card',
    publisher: 'OpenAI',
    kind: 'system-card',
    asOf: '2026-08-04',
  },
  'gpt-6-astra': {
    url: 'https://deploymentsafety.openai.com/gpt-6-astra/vision',
    title: 'GPT-6 Astra system card',
    publisher: 'OpenAI',
    kind: 'system-card',
    asOf: '2026-09-04',
  },
}
