// AUTO-GENERATED by scripts/sync-model-catalog.mts. Do not edit by hand.
// Source: https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
// Last synced: 2026-06-23

export interface CatalogEntry {
  inputPricePerMTok: number
  outputPricePerMTok: number
  cacheReadPricePerMTok?: number
  cacheCreationPricePerMTok?: number
  contextWindow: number
  maxOutputTokens: number
}

export const MODEL_CATALOG: Record<string, CatalogEntry> = {
  'claude-haiku-4-5': {
    inputPricePerMTok: 1,
    outputPricePerMTok: 5,
    cacheReadPricePerMTok: 0.1,
    cacheCreationPricePerMTok: 1.25,
    contextWindow: 200000,
    maxOutputTokens: 64000,
  },
  'claude-opus-4-8': {
    inputPricePerMTok: 5,
    outputPricePerMTok: 25,
    cacheReadPricePerMTok: 0.5,
    cacheCreationPricePerMTok: 6.25,
    contextWindow: 1000000,
    maxOutputTokens: 128000,
  },
  'claude-sonnet-4-6': {
    inputPricePerMTok: 3,
    outputPricePerMTok: 15,
    cacheReadPricePerMTok: 0.3,
    cacheCreationPricePerMTok: 3.75,
    contextWindow: 1000000,
    maxOutputTokens: 64000,
  },
  'gpt-4o': {
    inputPricePerMTok: 2.5,
    outputPricePerMTok: 10,
    contextWindow: 128000,
    maxOutputTokens: 16384,
  },
  'gpt-4o-mini': {
    inputPricePerMTok: 0.15,
    outputPricePerMTok: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16384,
  },
  'gpt-5': {
    inputPricePerMTok: 1.25,
    outputPricePerMTok: 10,
    contextWindow: 272000,
    maxOutputTokens: 128000,
  },
  'gpt-5-mini': {
    inputPricePerMTok: 0.25,
    outputPricePerMTok: 2,
    contextWindow: 272000,
    maxOutputTokens: 128000,
  },
}
