// AUTO-GENERATED by scripts/sync-model-cards.mts. Do not edit by hand.
// Vendor-published model cards / system cards, keyed by canonical model id.
// Source of truth: scripts/data/model-cards.json.
// Absent models mean "no sourced card yet", and the UI shows no link.
// Last synced: 2026-08-04

/** Whether a link is a card about this model, or a vendor hub listing cards. */
export type ModelCardKind = 'system-card' | 'model-card' | 'index'

export interface ModelCard {
  /** The vendor's own published page or PDF. */
  url: string
  /** Human title for the link. */
  title: string
  /** Who published it, e.g. "Anthropic". */
  publisher: string
  kind: ModelCardKind
  /**
   * ISO date the link was last reviewed. Absent on a card derived at lookup
   * time from the model id itself (see `huggingFaceCardUrl`), which is as
   * current as the id is.
   */
  asOf?: string
}

export const MODEL_CARDS: Record<string, ModelCard> = {
  'claude-fable-5': {
    url: 'https://www.anthropic.com/transparency',
    title: 'Anthropic transparency hub',
    publisher: 'Anthropic',
    kind: 'index',
    asOf: '2026-08-04',
  },
  'claude-haiku-4-5': {
    url: 'https://www.anthropic.com/transparency',
    title: 'Anthropic transparency hub',
    publisher: 'Anthropic',
    kind: 'index',
    asOf: '2026-08-04',
  },
  'claude-opus-4-8': {
    url: 'https://www.anthropic.com/transparency',
    title: 'Anthropic transparency hub',
    publisher: 'Anthropic',
    kind: 'index',
    asOf: '2026-08-04',
  },
  'claude-sonnet-4-6': {
    url: 'https://www.anthropic.com/transparency',
    title: 'Anthropic transparency hub',
    publisher: 'Anthropic',
    kind: 'index',
    asOf: '2026-08-04',
  },
  'claude-sonnet-5': {
    url: 'https://www.anthropic.com/transparency',
    title: 'Anthropic transparency hub',
    publisher: 'Anthropic',
    kind: 'index',
    asOf: '2026-08-04',
  },
  'gpt-4o': {
    url: 'https://openai.com/index/gpt-4o-system-card/',
    title: 'GPT-4o system card',
    publisher: 'OpenAI',
    kind: 'system-card',
    asOf: '2026-08-04',
  },
}
