import { createHash, type Hash } from 'node:crypto'
import * as fsp from 'node:fs/promises'
import { join, relative, resolve } from 'node:path'
import { z } from 'zod'
import { decodeWithSchema, safeJsonParse } from './lib/safe-json.mts'

/** Pinned upstream commit from https://github.com/cursor/plugins. */
export const BUNDLED_CURSOR_PLUGINS_COMMIT = 'e46364b8be46000b7df0f260550cd712afbb8d36'
export const BUNDLED_CURSOR_PLUGINS_REPO = 'cursor/plugins'
export const BUNDLED_CURSOR_SKILLS_VENDOR_DIR = resolve('vendor/bundled-cursor-skills')

const RAW_BASE = `https://raw.githubusercontent.com/${BUNDLED_CURSOR_PLUGINS_REPO}/${BUNDLED_CURSOR_PLUGINS_COMMIT}`
const API_BASE = `https://api.github.com/repos/${BUNDLED_CURSOR_PLUGINS_REPO}/contents`
const SOURCE_REPOSITORY = `https://github.com/${BUNDLED_CURSOR_PLUGINS_REPO}`
const SHA256_RE = /^[a-f0-9]{64}$/
const SNAPSHOT_README = `# Bundled Cursor skills snapshot

This directory is a checked-in release input generated by \`pnpm sync:cursor-skills\` from the
commit recorded in \`SOURCE.json\`. Normal installs and builds do not access the network.

Each plugin retains its upstream manifest and license. The snapshot contains only those files and
each skill's \`SKILL.md\`; \`SOURCE.json\` records a deterministic SHA-256 digest of that payload.
Do not edit generated files by hand.
`

const GITHUB_HEADERS = {
  Accept: 'application/vnd.github+json',
  'User-Agent': 'copse-panel-bundled-skills-sync',
  'X-GitHub-Api-Version': '2022-11-28',
} as const

interface MarketplaceManifest {
  plugins: { name: string; source: string }[]
}

interface GitHubContentEntry {
  name: string
  type: 'file' | 'dir' | 'symlink' | 'submodule'
}

const marketplaceManifestSchema: z.ZodType<MarketplaceManifest> = z.object({
  plugins: z.array(z.object({ name: z.string(), source: z.string() })),
})

const gitHubContentEntriesSchema: z.ZodType<GitHubContentEntry[]> = z.array(
  z.object({
    name: z.string(),
    type: z.enum(['file', 'dir', 'symlink', 'submodule']),
  }),
)

const pluginManifestSchema = z.object({
  name: z.string().min(1),
  license: z.string().min(1),
  skills: z.string().min(1),
})

export interface BundledCursorSkillsSource {
  repository: string
  commit: string
  pluginCount: number
  skillCount: number
  contentSha256: string
  slim: true
}

export const bundledCursorSkillsSourceSchema: z.ZodType<BundledCursorSkillsSource> = z.object({
  repository: z.string(),
  commit: z.string(),
  pluginCount: z.number().int().positive(),
  skillCount: z.number().int().positive(),
  contentSha256: z.string().regex(SHA256_RE),
  slim: z.literal(true),
})

class GitHubFetchError extends Error {
  readonly status: number

  constructor(status: number, url: string) {
    super(`GitHub fetch failed (${String(status)}): ${url}`)
    this.status = status
  }
}

async function fetchJson<T>(url: string, schema: z.ZodType<T>): Promise<T> {
  const response = await fetch(url, { headers: GITHUB_HEADERS })
  if (!response.ok) throw new GitHubFetchError(response.status, url)
  return schema.parse(await response.json())
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) throw new GitHubFetchError(response.status, url)
  return response.text()
}

function safeName(value: string, label: string): string {
  if (value.length === 0 || value === '.' || value === '..' || /[\\/]/.test(value)) {
    throw new Error(`Unsafe ${label}: ${JSON.stringify(value)}`)
  }
  return value
}

async function listSkillDirs(pluginSource: string): Promise<string[]> {
  const url = `${API_BASE}/${pluginSource}/skills?ref=${BUNDLED_CURSOR_PLUGINS_COMMIT}`
  try {
    const entries = await fetchJson(url, gitHubContentEntriesSchema)
    return entries
      .filter((entry) => entry.type === 'dir')
      .map((entry) => safeName(entry.name, 'skill directory'))
      .sort()
  } catch (error) {
    if (error instanceof GitHubFetchError && error.status === 404) return []
    throw error
  }
}

function updateFrame(hash: Hash, label: string, value: string): void {
  hash.update(`${String(label.length)}:${label}${String(value.length)}:${value}`)
}

async function snapshotFiles(root: string): Promise<string[]> {
  const files: string[] = []
  const visit = async (directory: string): Promise<void> => {
    for (const entry of await fsp.readdir(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name)
      if (entry.isSymbolicLink())
        throw new Error(`Bundled Cursor snapshot contains symlink: ${path}`)
      if (entry.isDirectory()) await visit(path)
      else if (entry.isFile()) files.push(relative(root, path).replaceAll('\\', '/'))
      else throw new Error(`Bundled Cursor snapshot contains unsupported entry: ${path}`)
    }
  }
  await visit(resolve(root, 'plugins'))
  return files.sort()
}

/** Digest the complete distributable payload, excluding SOURCE.json itself. */
export async function hashBundledCursorSkillsTree(root: string): Promise<string> {
  const hash = createHash('sha256')
  updateFrame(hash, 'schema', 'copse-bundled-cursor-skills-v1')
  for (const path of await snapshotFiles(root)) {
    const bytes = await fsp.readFile(resolve(root, path))
    updateFrame(hash, 'path', path)
    updateFrame(hash, 'size', String(bytes.length))
    hash.update(bytes)
  }
  return hash.digest('hex')
}

async function snapshotCounts(root: string): Promise<{ pluginCount: number; skillCount: number }> {
  const pluginsDir = resolve(root, 'plugins')
  const plugins = (await fsp.readdir(pluginsDir, { withFileTypes: true })).sort((a, b) =>
    a.name.localeCompare(b.name),
  )
  let pluginCount = 0
  let skillCount = 0

  for (const plugin of plugins) {
    if (!plugin.isDirectory()) throw new Error(`Unexpected file in plugins/: ${plugin.name}`)
    const pluginRoot = join(pluginsDir, plugin.name)
    const rawManifest = await fsp.readFile(
      join(pluginRoot, '.cursor-plugin', 'plugin.json'),
      'utf8',
    )
    const manifest = safeJsonParse(rawManifest, decodeWithSchema(pluginManifestSchema))
    if (manifest === null) throw new Error(`Invalid plugin manifest: ${plugin.name}`)
    if (manifest.name !== plugin.name) {
      throw new Error(`Plugin directory ${plugin.name} contains manifest for ${manifest.name}`)
    }
    await fsp.access(join(pluginRoot, 'LICENSE'))

    const skills = await fsp.readdir(join(pluginRoot, 'skills'), { withFileTypes: true })
    if (skills.length === 0) throw new Error(`Bundled plugin has no skills: ${plugin.name}`)
    for (const skill of skills) {
      if (!skill.isDirectory()) throw new Error(`Unexpected file in ${plugin.name}/skills`)
      await fsp.access(join(pluginRoot, 'skills', skill.name, 'SKILL.md'))
      skillCount++
    }
    pluginCount++
  }

  if (pluginCount === 0 || skillCount === 0) throw new Error('Bundled Cursor snapshot is empty')
  return { pluginCount, skillCount }
}

export async function readBundledCursorSkillsSource(
  root: string,
): Promise<BundledCursorSkillsSource> {
  const raw = await fsp.readFile(resolve(root, 'SOURCE.json'), 'utf8')
  const source = safeJsonParse(raw, decodeWithSchema(bundledCursorSkillsSourceSchema))
  if (source === null) throw new Error(`Invalid bundled Cursor source manifest: ${root}`)
  return source
}

/** Validate provenance, inventory, and every vendored payload byte. */
export async function assertBundledCursorSkillsSnapshot(
  root = BUNDLED_CURSOR_SKILLS_VENDOR_DIR,
): Promise<BundledCursorSkillsSource> {
  await fsp.access(resolve(root, 'README.md'))
  const source = await readBundledCursorSkillsSource(root)
  if (source.repository !== SOURCE_REPOSITORY) {
    throw new Error(`Unexpected bundled Cursor repository: ${source.repository}`)
  }
  if (source.commit !== BUNDLED_CURSOR_PLUGINS_COMMIT) {
    throw new Error(
      `Bundled Cursor snapshot is at ${source.commit}; expected ${BUNDLED_CURSOR_PLUGINS_COMMIT}`,
    )
  }
  const counts = await snapshotCounts(root)
  if (counts.pluginCount !== source.pluginCount || counts.skillCount !== source.skillCount) {
    throw new Error(
      `Bundled Cursor inventory mismatch: found ${String(counts.pluginCount)} plugins/` +
        `${String(counts.skillCount)} skills; SOURCE.json records ${String(source.pluginCount)}/` +
        String(source.skillCount),
    )
  }
  const contentSha256 = await hashBundledCursorSkillsTree(root)
  if (contentSha256 !== source.contentSha256) {
    throw new Error(
      `Bundled Cursor content hash mismatch: found ${contentSha256}; ` +
        `SOURCE.json records ${source.contentSha256}`,
    )
  }
  return source
}

/** Download the pinned, slim plugin snapshot for an explicit source update. */
export async function syncBundledCursorSkills(
  snapshotDir: string,
): Promise<BundledCursorSkillsSource> {
  const marketplace = await fetchJson(
    `${RAW_BASE}/.cursor-plugin/marketplace.json`,
    marketplaceManifestSchema,
  )

  const pluginsDir = join(snapshotDir, 'plugins')
  await fsp.rm(snapshotDir, { recursive: true, force: true })
  await fsp.mkdir(pluginsDir, { recursive: true })
  await fsp.writeFile(join(snapshotDir, 'README.md'), SNAPSHOT_README, 'utf8')

  for (const entry of marketplace.plugins) {
    const pluginSource = safeName(entry.source, 'plugin source')
    const skillDirs = await listSkillDirs(pluginSource)
    if (skillDirs.length === 0) continue

    const manifestRaw = await fetchText(`${RAW_BASE}/${pluginSource}/.cursor-plugin/plugin.json`)
    const manifest = safeJsonParse(manifestRaw, decodeWithSchema(pluginManifestSchema))
    if (manifest === null) throw new Error(`Invalid plugin manifest: ${pluginSource}`)
    if (manifest.name !== pluginSource) {
      throw new Error(`Marketplace source ${pluginSource} contains manifest for ${manifest.name}`)
    }
    const license = await fetchText(`${RAW_BASE}/${pluginSource}/LICENSE`)

    const destination = join(pluginsDir, pluginSource)
    await fsp.mkdir(join(destination, '.cursor-plugin'), { recursive: true })
    await fsp.writeFile(join(destination, '.cursor-plugin', 'plugin.json'), manifestRaw, 'utf8')
    await fsp.writeFile(join(destination, 'LICENSE'), license, 'utf8')

    for (const skillName of skillDirs) {
      const body = await fetchText(`${RAW_BASE}/${pluginSource}/skills/${skillName}/SKILL.md`)
      const skillDir = join(destination, 'skills', skillName)
      await fsp.mkdir(skillDir, { recursive: true })
      await fsp.writeFile(join(skillDir, 'SKILL.md'), body, 'utf8')
    }
  }

  const counts = await snapshotCounts(snapshotDir)
  const source: BundledCursorSkillsSource = {
    repository: SOURCE_REPOSITORY,
    commit: BUNDLED_CURSOR_PLUGINS_COMMIT,
    ...counts,
    contentSha256: await hashBundledCursorSkillsTree(snapshotDir),
    slim: true,
  }
  await fsp.writeFile(
    join(snapshotDir, 'SOURCE.json'),
    `${JSON.stringify(source, null, 2)}\n`,
    'utf8',
  )
  await assertBundledCursorSkillsSnapshot(snapshotDir)
  return source
}
