import { createHash, type Hash } from 'node:crypto'
import * as fsp from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import { z } from 'zod'
import { decodeWithSchema, safeJsonParse } from './lib/safe-json.mts'
import { extractSkillFileReferences } from '../src/shared/skills/extract-skill-references.mts'

/** Pinned upstream commit from https://github.com/cursor/plugins. */
export const BUNDLED_CURSOR_PLUGINS_COMMIT = 'e46364b8be46000b7df0f260550cd712afbb8d36'
export const BUNDLED_CURSOR_PLUGINS_REPO = 'cursor/plugins'
export const BUNDLED_CURSOR_SKILLS_VENDOR_DIR = resolve('vendor/bundled-cursor-skills')

const RAW_BASE = `https://raw.githubusercontent.com/${BUNDLED_CURSOR_PLUGINS_REPO}/${BUNDLED_CURSOR_PLUGINS_COMMIT}`
const TREE_URL = `https://api.github.com/repos/${BUNDLED_CURSOR_PLUGINS_REPO}/git/trees/${BUNDLED_CURSOR_PLUGINS_COMMIT}?recursive=1`
const SOURCE_REPOSITORY = `https://github.com/${BUNDLED_CURSOR_PLUGINS_REPO}`
const SHA256_RE = /^[a-f0-9]{64}$/
const SNAPSHOT_README = `# Bundled Cursor skills snapshot

This directory is a checked-in release input generated by \`pnpm sync:cursor-skills\` from the
commit recorded in \`SOURCE.json\`. Normal installs and builds do not access the network.

Each plugin retains its upstream manifest and license. The snapshot contains those files, each
skill's \`SKILL.md\`, and the files under a skill's directory that its text names (followed through
the files it pulls in). A script that belongs to a JS/TS project inside the skill is left out, since
one file of a project cannot run on its own. \`SOURCE.json\` records a deterministic SHA-256 digest of
the payload and every reference that is still missing, which the build re-checks.
Do not edit generated files by hand.
`

const GITHUB_HEADERS = {
  Accept: 'application/vnd.github+json',
  'User-Agent': 'copse-panel-bundled-skills-sync',
  'X-GitHub-Api-Version': '2022-11-28',
} as const

interface MarketplaceManifest {
  plugins: { name: string; source: string }[]
}

interface GitTree {
  truncated: boolean
  tree: { path: string; type: string }[]
}

const marketplaceManifestSchema: z.ZodType<MarketplaceManifest> = z.object({
  plugins: z.array(z.object({ name: z.string(), source: z.string() })),
})

const gitTreeSchema: z.ZodType<GitTree> = z.object({
  truncated: z.boolean(),
  tree: z.array(z.object({ path: z.string(), type: z.string() })),
})

const pluginManifestSchema = z.object({
  name: z.string().min(1),
  license: z.string().min(1),
  skills: z.string().min(1),
})

export interface BundledCursorSkillsSource {
  repository: string
  commit: string
  pluginCount: number
  skillCount: number
  contentSha256: string
  /** Skills ship with the files their text references, not SKILL.md alone. */
  skillFiles: 'referenced'
  /**
   * `plugin/skill` → bundle paths its SKILL.md names that are not in the
   * snapshot (absent upstream, or part of an excluded script project). The
   * build fails when this drifts, so a new dangling reference is a reviewed
   * change rather than a runtime surprise.
   */
  danglingReferences: Record<string, string[]>
}

export const bundledCursorSkillsSourceSchema: z.ZodType<BundledCursorSkillsSource> = z.object({
  repository: z.string(),
  commit: z.string(),
  pluginCount: z.number().int().positive(),
  skillCount: z.number().int().positive(),
  contentSha256: z.string().regex(SHA256_RE),
  skillFiles: z.literal('referenced'),
  danglingReferences: z.record(z.string(), z.array(z.string())),
})

/** Upper bound for one vendored skill file; a larger one is not a prompt reference. */
const MAX_SKILL_FILE_BYTES = 256 * 1024

class GitHubFetchError extends Error {
  readonly status: number

  constructor(status: number, url: string) {
    super(`GitHub fetch failed (${String(status)}): ${url}`)
    this.status = status
  }
}

async function fetchJson<T>(url: string, schema: z.ZodType<T>): Promise<T> {
  const response = await fetch(url, { headers: GITHUB_HEADERS })
  if (!response.ok) throw new GitHubFetchError(response.status, url)
  return schema.parse(await response.json())
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) throw new GitHubFetchError(response.status, url)
  return response.text()
}

async function fetchBytes(url: string): Promise<Buffer> {
  const response = await fetch(url)
  if (!response.ok) throw new GitHubFetchError(response.status, url)
  const bytes = Buffer.from(await response.arrayBuffer())
  if (bytes.length > MAX_SKILL_FILE_BYTES) {
    throw new Error(`Skill file exceeds ${String(MAX_SKILL_FILE_BYTES)} bytes: ${url}`)
  }
  return bytes
}

function safeName(value: string, label: string): string {
  if (value.length === 0 || value === '.' || value === '..' || /[\\/]/.test(value)) {
    throw new Error(`Unsafe ${label}: ${JSON.stringify(value)}`)
  }
  return value
}

async function fetchUpstreamFiles(): Promise<string[]> {
  const tree = await fetchJson(TREE_URL, gitTreeSchema)
  if (tree.truncated) throw new Error(`GitHub truncated the tree listing: ${TREE_URL}`)
  return tree.tree.filter((entry) => entry.type === 'blob').map((entry) => entry.path)
}

/** Skill directories of one plugin: every `<plugin>/skills/<name>/SKILL.md` upstream. */
function listSkillDirs(upstreamFiles: readonly string[], pluginSource: string): string[] {
  const prefix = `${pluginSource}/skills/`
  const names = new Set<string>()
  for (const path of upstreamFiles) {
    if (!path.startsWith(prefix)) continue
    const rest = path.slice(prefix.length).split('/')
    if (rest.length === 2 && rest[1] === 'SKILL.md' && rest[0]) {
      names.add(safeName(rest[0], 'skill directory'))
    }
  }
  return [...names].sort()
}

const SCRIPT_PROJECT_MARKERS = [
  'package.json',
  'bun.lock',
  'bun.lockb',
  'package-lock.json',
  'pnpm-lock.yaml',
  'yarn.lock',
]

/**
 * Whether a skill file sits in a JS/TS project inside the skill (a package
 * manifest or lockfile in one of its directories). One file of a project
 * cannot run without the rest, so such files are never vendored piecemeal.
 */
function belongsToScriptProject(path: string, skillFiles: ReadonlySet<string>): boolean {
  const parts = path.split('/')
  for (let depth = 1; depth < parts.length; depth++) {
    const dir = parts.slice(0, depth).join('/')
    if (SCRIPT_PROJECT_MARKERS.some((marker) => skillFiles.has(`${dir}/${marker}`))) return true
  }
  return false
}

function escapeRegExp(text: string): string {
  return text.replace(/[.+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Path-shaped globs and placeholders in a text — `references/sources/*.md`,
 * `references/sources/<source>.md` — as matchers over skill-relative paths.
 */
function pathPatterns(text: string): RegExp[] {
  const patterns: RegExp[] = []
  for (const [token] of text.matchAll(/[\w.-]+(?:\/[\w.<>*-]+)+/g)) {
    if (!/[*<]/.test(token)) continue
    const source = token
      .split(/(\*|<[^>/]*>)/)
      .map((part) => (part === '*' ? '[^/]*' : part.startsWith('<') ? '[^/]+' : escapeRegExp(part)))
      .join('')
    patterns.push(new RegExp(`^${source}$`))
  }
  return patterns
}

/** Skill-relative candidate paths a text names, literally or through a glob/placeholder. */
export function mentionedSkillFiles(text: string, candidates: readonly string[]): string[] {
  const patterns = pathPatterns(text)
  return candidates.filter(
    (candidate) => text.includes(candidate) || patterns.some((pattern) => pattern.test(candidate)),
  )
}

/**
 * Vendor the files under one skill directory that its SKILL.md names, then the
 * files those name in turn. Returns the skill-relative paths written.
 */
async function syncReferencedSkillFiles(
  upstreamFiles: readonly string[],
  pluginSource: string,
  skillName: string,
  skillBody: string,
  skillDir: string,
): Promise<string[]> {
  const prefix = `${pluginSource}/skills/${skillName}/`
  const skillFiles = new Set(
    upstreamFiles
      .filter((path) => path.startsWith(prefix))
      .map((path) => path.slice(prefix.length)),
  )
  const candidates = [...skillFiles]
    .filter((path) => path !== 'SKILL.md' && !belongsToScriptProject(path, skillFiles))
    .sort()
  const written = new Set<string>()
  const pending = [skillBody]
  for (let text = pending.shift(); text !== undefined; text = pending.shift()) {
    for (const path of mentionedSkillFiles(text, candidates)) {
      if (written.has(path)) continue
      written.add(path)
      const bytes = await fetchBytes(`${RAW_BASE}/${prefix}${path}`)
      const target = join(skillDir, ...path.split('/'))
      await fsp.mkdir(dirname(target), { recursive: true })
      await fsp.writeFile(target, bytes)
      pending.push(bytes.toString('utf8'))
    }
  }
  return [...written].sort()
}

function updateFrame(hash: Hash, label: string, value: string): void {
  hash.update(`${String(label.length)}:${label}${String(value.length)}:${value}`)
}

async function snapshotFiles(root: string): Promise<string[]> {
  const files: string[] = []
  const visit = async (directory: string): Promise<void> => {
    for (const entry of await fsp.readdir(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name)
      if (entry.isSymbolicLink())
        throw new Error(`Bundled Cursor snapshot contains symlink: ${path}`)
      if (entry.isDirectory()) await visit(path)
      else if (entry.isFile()) files.push(relative(root, path).replaceAll('\\', '/'))
      else throw new Error(`Bundled Cursor snapshot contains unsupported entry: ${path}`)
    }
  }
  await visit(resolve(root, 'plugins'))
  return files.sort()
}

/** Digest the complete distributable payload, excluding SOURCE.json itself. */
export async function hashBundledCursorSkillsTree(root: string): Promise<string> {
  const hash = createHash('sha256')
  updateFrame(hash, 'schema', 'copse-bundled-cursor-skills-v1')
  for (const path of await snapshotFiles(root)) {
    const bytes = await fsp.readFile(resolve(root, path))
    updateFrame(hash, 'path', path)
    updateFrame(hash, 'size', String(bytes.length))
    hash.update(bytes)
  }
  return hash.digest('hex')
}

async function snapshotCounts(root: string): Promise<{ pluginCount: number; skillCount: number }> {
  const pluginsDir = resolve(root, 'plugins')
  const plugins = (await fsp.readdir(pluginsDir, { withFileTypes: true })).sort((a, b) =>
    a.name.localeCompare(b.name),
  )
  let pluginCount = 0
  let skillCount = 0

  for (const plugin of plugins) {
    if (!plugin.isDirectory()) throw new Error(`Unexpected file in plugins/: ${plugin.name}`)
    const pluginRoot = join(pluginsDir, plugin.name)
    const rawManifest = await fsp.readFile(
      join(pluginRoot, '.cursor-plugin', 'plugin.json'),
      'utf8',
    )
    const manifest = safeJsonParse(rawManifest, decodeWithSchema(pluginManifestSchema))
    if (manifest === null) throw new Error(`Invalid plugin manifest: ${plugin.name}`)
    if (manifest.name !== plugin.name) {
      throw new Error(`Plugin directory ${plugin.name} contains manifest for ${manifest.name}`)
    }
    await fsp.access(join(pluginRoot, 'LICENSE'))

    const skills = await fsp.readdir(join(pluginRoot, 'skills'), { withFileTypes: true })
    if (skills.length === 0) throw new Error(`Bundled plugin has no skills: ${plugin.name}`)
    for (const skill of skills) {
      if (!skill.isDirectory()) throw new Error(`Unexpected file in ${plugin.name}/skills`)
      await fsp.access(join(pluginRoot, 'skills', skill.name, 'SKILL.md'))
      skillCount++
    }
    pluginCount++
  }

  if (pluginCount === 0 || skillCount === 0) throw new Error('Bundled Cursor snapshot is empty')
  return { pluginCount, skillCount }
}

/** Bundle paths each vendored SKILL.md names that the snapshot does not contain. */
export async function findDanglingSkillReferences(root: string): Promise<Record<string, string[]>> {
  const pluginsDir = resolve(root, 'plugins')
  const dangling: Record<string, string[]> = {}
  for (const plugin of (await fsp.readdir(pluginsDir)).sort()) {
    const skillsDir = join(pluginsDir, plugin, 'skills')
    for (const skill of (await fsp.readdir(skillsDir)).sort()) {
      const skillDir = join(skillsDir, skill)
      const body = await fsp.readFile(join(skillDir, 'SKILL.md'), 'utf8')
      const missing: string[] = []
      for (const reference of extractSkillFileReferences(body)) {
        try {
          await fsp.access(join(skillDir, ...reference.split('/')))
        } catch {
          missing.push(reference)
        }
      }
      if (missing.length > 0) dangling[`${plugin}/${skill}`] = missing
    }
  }
  return dangling
}

export async function readBundledCursorSkillsSource(
  root: string,
): Promise<BundledCursorSkillsSource> {
  const raw = await fsp.readFile(resolve(root, 'SOURCE.json'), 'utf8')
  const source = safeJsonParse(raw, decodeWithSchema(bundledCursorSkillsSourceSchema))
  if (source === null) throw new Error(`Invalid bundled Cursor source manifest: ${root}`)
  return source
}

/** Validate provenance, inventory, and every vendored payload byte. */
export async function assertBundledCursorSkillsSnapshot(
  root = BUNDLED_CURSOR_SKILLS_VENDOR_DIR,
): Promise<BundledCursorSkillsSource> {
  await fsp.access(resolve(root, 'README.md'))
  const source = await readBundledCursorSkillsSource(root)
  if (source.repository !== SOURCE_REPOSITORY) {
    throw new Error(`Unexpected bundled Cursor repository: ${source.repository}`)
  }
  if (source.commit !== BUNDLED_CURSOR_PLUGINS_COMMIT) {
    throw new Error(
      `Bundled Cursor snapshot is at ${source.commit}; expected ${BUNDLED_CURSOR_PLUGINS_COMMIT}`,
    )
  }
  const counts = await snapshotCounts(root)
  if (counts.pluginCount !== source.pluginCount || counts.skillCount !== source.skillCount) {
    throw new Error(
      `Bundled Cursor inventory mismatch: found ${String(counts.pluginCount)} plugins/` +
        `${String(counts.skillCount)} skills; SOURCE.json records ${String(source.pluginCount)}/` +
        String(source.skillCount),
    )
  }
  const contentSha256 = await hashBundledCursorSkillsTree(root)
  if (contentSha256 !== source.contentSha256) {
    throw new Error(
      `Bundled Cursor content hash mismatch: found ${contentSha256}; ` +
        `SOURCE.json records ${source.contentSha256}`,
    )
  }
  const dangling = await findDanglingSkillReferences(root)
  if (JSON.stringify(dangling) !== JSON.stringify(source.danglingReferences)) {
    throw new Error(
      `Bundled Cursor skills' missing references changed: found ${JSON.stringify(dangling)}; ` +
        `SOURCE.json records ${JSON.stringify(source.danglingReferences)}`,
    )
  }
  return source
}

/** Download the pinned plugin snapshot for an explicit source update. */
export async function syncBundledCursorSkills(
  snapshotDir: string,
): Promise<BundledCursorSkillsSource> {
  const marketplace = await fetchJson(
    `${RAW_BASE}/.cursor-plugin/marketplace.json`,
    marketplaceManifestSchema,
  )

  const upstreamFiles = await fetchUpstreamFiles()

  const pluginsDir = join(snapshotDir, 'plugins')
  await fsp.rm(snapshotDir, { recursive: true, force: true })
  await fsp.mkdir(pluginsDir, { recursive: true })
  await fsp.writeFile(join(snapshotDir, 'README.md'), SNAPSHOT_README, 'utf8')

  for (const entry of marketplace.plugins) {
    const pluginSource = safeName(entry.source, 'plugin source')
    const skillDirs = listSkillDirs(upstreamFiles, pluginSource)
    if (skillDirs.length === 0) continue

    const manifestRaw = await fetchText(`${RAW_BASE}/${pluginSource}/.cursor-plugin/plugin.json`)
    const manifest = safeJsonParse(manifestRaw, decodeWithSchema(pluginManifestSchema))
    if (manifest === null) throw new Error(`Invalid plugin manifest: ${pluginSource}`)
    if (manifest.name !== pluginSource) {
      throw new Error(`Marketplace source ${pluginSource} contains manifest for ${manifest.name}`)
    }
    const license = await fetchText(`${RAW_BASE}/${pluginSource}/LICENSE`)

    const destination = join(pluginsDir, pluginSource)
    await fsp.mkdir(join(destination, '.cursor-plugin'), { recursive: true })
    await fsp.writeFile(join(destination, '.cursor-plugin', 'plugin.json'), manifestRaw, 'utf8')
    await fsp.writeFile(join(destination, 'LICENSE'), license, 'utf8')

    for (const skillName of skillDirs) {
      const body = await fetchText(`${RAW_BASE}/${pluginSource}/skills/${skillName}/SKILL.md`)
      const skillDir = join(destination, 'skills', skillName)
      await fsp.mkdir(skillDir, { recursive: true })
      await fsp.writeFile(join(skillDir, 'SKILL.md'), body, 'utf8')
      await syncReferencedSkillFiles(upstreamFiles, pluginSource, skillName, body, skillDir)
    }
  }

  const counts = await snapshotCounts(snapshotDir)
  const source: BundledCursorSkillsSource = {
    repository: SOURCE_REPOSITORY,
    commit: BUNDLED_CURSOR_PLUGINS_COMMIT,
    ...counts,
    contentSha256: await hashBundledCursorSkillsTree(snapshotDir),
    skillFiles: 'referenced',
    danglingReferences: await findDanglingSkillReferences(snapshotDir),
  }
  await fsp.writeFile(
    join(snapshotDir, 'SOURCE.json'),
    `${JSON.stringify(source, null, 2)}\n`,
    'utf8',
  )
  await assertBundledCursorSkillsSnapshot(snapshotDir)
  return source
}
