import { execFile } from 'node:child_process'
import { mkdir, writeFile } from 'node:fs/promises'
import { hostname, platform, release } from 'node:os'
import { dirname, resolve } from 'node:path'
import { promisify } from 'node:util'
import { KNOWN_ACP_AGENTS } from '../src/shared/acp-known-agents.ts'
import {
  defaultBlockingMcpToolPrompt,
  defaultBlockingReadPrompt,
  defaultLongRunPrompt,
  probeAgentLongRun,
  type AcpLongRunProbeMode,
  type AcpLongRunReport,
} from '../src/main/services/acp/acp-long-run-probe.ts'

/**
 * Long-running ACP liveness probe. Sends one prompt per agent that asks the
 * agent to remain active for several minutes and emit periodic progress text.
 * This spends model tokens and intentionally takes a long time.
 *
 * Flags:
 *   --agent <id>       Probe only this catalog agent (repeatable). Default: all installed.
 *   --all              Also attempt agents not found on PATH.
 *   --duration <ms>    Requested per-agent run duration (default 360000 = 6 min).
 *   --interval <ms>    Requested progress interval (default 30000).
 *   --timeout <ms>     Per-agent hard timeout (default duration + 90000).
 *   --mode <mode>      stream | blocking-fs-read | blocking-mcp-tool (default: stream).
 *   --out <path>       Basename for outputs; writes <path>.md and <path>.json.
 *                      Default: docs/acp-long-run-matrix
 *   --no-write         Print only; don't write files.
 *   --prompt <text>    Override the default long-run prompt.
 */

const run = promisify(execFile)

interface Args {
  agents: string[]
  all: boolean
  durationMs: number
  intervalMs: number
  timeoutMs: number | null
  mode: AcpLongRunProbeMode
  out: string
  write: boolean
  prompt: string | null
}

function parseMode(value: string): AcpLongRunProbeMode {
  if (value === 'stream' || value === 'blocking-fs-read' || value === 'blocking-mcp-tool') {
    return value
  }
  throw new Error(`Unsupported long-run probe mode: ${value}`)
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    agents: [],
    all: false,
    durationMs: 360_000,
    intervalMs: 30_000,
    timeoutMs: null,
    mode: 'stream',
    out: 'docs/acp-long-run-matrix',
    write: true,
    prompt: null,
  }
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i]
    if (flag === '--agent') args.agents.push(argv[++i] ?? '')
    else if (flag === '--all') args.all = true
    else if (flag === '--duration') args.durationMs = Number(argv[++i] ?? args.durationMs)
    else if (flag === '--interval') args.intervalMs = Number(argv[++i] ?? args.intervalMs)
    else if (flag === '--timeout') args.timeoutMs = Number(argv[++i] ?? '')
    else if (flag === '--mode') args.mode = parseMode(argv[++i] ?? args.mode)
    else if (flag === '--out') args.out = argv[++i] ?? args.out
    else if (flag === '--no-write') args.write = false
    else if (flag === '--prompt') args.prompt = argv[++i] ?? args.prompt
  }
  args.agents = args.agents.filter(Boolean)
  return args
}

async function resolveOnPath(command: string): Promise<string | null> {
  const finder = process.platform === 'win32' ? 'where' : 'which'
  try {
    const { stdout } = await run(finder, [command], { timeout: 4000 })
    const first = stdout.split(/\r?\n/).find((line) => line.trim().length > 0)
    return first ? first.trim() : null
  } catch {
    return null
  }
}

function envFor(envHints: readonly string[] | undefined): Record<string, string> | undefined {
  if (!envHints || envHints.length === 0) return undefined
  const env: Record<string, string> = {}
  for (const name of envHints) {
    const value = process.env[name]
    if (value) env[name] = value
  }
  return Object.keys(env).length > 0 ? env : undefined
}

function fmtMs(ms: number | null | undefined): string {
  if (ms === null || ms === undefined) return '·'
  if (ms < 1000) return `${String(ms)}ms`
  return `${(ms / 1000).toFixed(1)}s`
}

function cell(report: AcpLongRunReport, value: string): string {
  return report.ok ? value : '—'
}

function renderMarkdown(
  reports: readonly AcpLongRunReport[],
  meta: { probedAt: string; host: string },
): string {
  const lines: string[] = []
  lines.push('# ACP agent long-run matrix')
  lines.push('')
  lines.push('> Generated by `npm run probe:acp:long`. Each agent receives one long-running')
  lines.push('> prompt intended to keep the ACP turn alive for several minutes while emitting')
  lines.push('> periodic progress updates. Spends model tokens; opt-in only.')
  lines.push('')
  lines.push(`- Probed at: ${meta.probedAt}`)
  lines.push(`- Host: ${meta.host}`)
  lines.push(`- Mode: ${reports[0]?.mode ?? 'stream'}`)
  lines.push('')
  if (reports.length === 0) {
    lines.push('_No agents were probed._')
    lines.push('')
    return lines.join('\n')
  }

  const header = ['Observation', ...reports.map((r) => r.title.replace(/\|/g, '\\|'))]
  lines.push(`| ${header.join(' | ')} |`)
  lines.push(`| ${header.map(() => '---').join(' | ')} |`)
  const rows: Array<[string, (r: AcpLongRunReport) => string]> = [
    ['Result', (r): string => (r.ok ? 'ok' : 'failed')],
    ['Elapsed', (r): string => fmtMs(r.elapsedMs)],
    ['Completed early', (r): string => cell(r, r.completedEarly ? 'yes' : 'no')],
    ['First update', (r): string => cell(r, fmtMs(r.firstUpdateAfterMs))],
    ['Last update', (r): string => cell(r, fmtMs(r.lastUpdateAfterMs))],
    ['Max silent gap', (r): string => cell(r, fmtMs(r.maxSilentGapMs))],
    ['Updates', (r): string => cell(r, String(r.updateCount))],
    ['Text chunks', (r): string => cell(r, String(r.textChunkCount))],
    ['Tool calls', (r): string => cell(r, String(r.toolCallCount))],
    ['fs/read_text_file calls', (r): string => cell(r, String(r.fsReadRequestCount))],
    ['MCP wait_for_liveness calls', (r): string => cell(r, String(r.mcpToolCallCount))],
    ['MCP wait_for_liveness completed', (r): string => cell(r, String(r.mcpToolCompletedCount))],
    [
      'MCP request closed before result',
      (r): string => cell(r, String(r.mcpToolClosedBeforeResultCount)),
    ],
    ['Permission requests', (r): string => cell(r, String(r.permissionRequests.length))],
    ['Stop reason', (r): string => cell(r, r.stopReason ?? '·')],
  ]
  for (const [label, value] of rows) {
    lines.push(`| ${[label, ...reports.map(value)].join(' | ')} |`)
  }

  lines.push('')
  lines.push('## Details')
  lines.push('')
  for (const report of reports) {
    lines.push(`### ${report.title} (\`${report.agentId}\`)`)
    lines.push('')
    lines.push(`- Command: \`${[report.command, ...report.args].join(' ')}\``)
    lines.push(`- Mode: \`${report.mode}\``)
    lines.push(`- Expected duration: ${fmtMs(report.expectedDurationMs)}`)
    lines.push(`- Elapsed: ${fmtMs(report.elapsedMs)}`)
    if (!report.ok) lines.push(`- **Probe failed:** ${report.error ?? 'unknown error'}`)
    else {
      lines.push(`- Stop reason: \`${report.stopReason ?? 'unknown'}\``)
      lines.push(`- Completed early: ${report.completedEarly ? 'yes' : 'no'}`)
    }
    lines.push(`- First update: ${fmtMs(report.firstUpdateAfterMs)}`)
    lines.push(`- Last update: ${fmtMs(report.lastUpdateAfterMs)}`)
    lines.push(`- Max silent gap: ${fmtMs(report.maxSilentGapMs)}`)
    lines.push(
      `- Updates: ${String(report.updateCount)} (${report.updateKinds.join(', ') || 'none'})`,
    )
    lines.push(`- Text chunks: ${String(report.textChunkCount)}`)
    lines.push(`- Tool calls: ${String(report.toolCallCount)}`)
    lines.push(`- fs/read_text_file calls: ${String(report.fsReadRequestCount)}`)
    lines.push(`- MCP wait_for_liveness calls: ${String(report.mcpToolCallCount)}`)
    lines.push(`- MCP wait_for_liveness completed: ${String(report.mcpToolCompletedCount)}`)
    lines.push(
      `- MCP request closed before result: ${String(report.mcpToolClosedBeforeResultCount)}`,
    )
    if (report.permissionRequests.length > 0) {
      for (const perm of report.permissionRequests) {
        lines.push(
          `- Permission: kind=\`${perm.kind}\` title=${JSON.stringify(perm.title ?? '')} ` +
            `options=[${perm.optionIds.join(', ')}] optionKinds=[${perm.optionKinds.join(', ')}]`,
        )
      }
    }
    lines.push('')
  }
  return lines.join('\n')
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2))
  const cwd = process.cwd()
  const catalog = args.agents.length
    ? KNOWN_ACP_AGENTS.filter((agent) => args.agents.includes(agent.id))
    : KNOWN_ACP_AGENTS

  if (args.agents.length) {
    const unknown = args.agents.filter((id) => !KNOWN_ACP_AGENTS.some((agent) => agent.id === id))
    if (unknown.length) console.warn(`Unknown agent id(s), skipping: ${unknown.join(', ')}`)
  }

  const targets = await Promise.all(
    catalog.map(async (agent) => ({ agent, path: await resolveOnPath(agent.command) })),
  )
  const toProbe = args.all ? targets : targets.filter((target) => target.path !== null)
  if (toProbe.length === 0) {
    console.log('No known ACP agents found on PATH. Install one (see `npm run detect:acp`),')
    console.log('or pass --all to record them as unavailable in the matrix.')
    return
  }

  const timeoutMs = args.timeoutMs ?? args.durationMs + 90_000
  const prompt =
    args.prompt ??
    (args.mode === 'blocking-fs-read'
      ? defaultBlockingReadPrompt(args.durationMs)
      : args.mode === 'blocking-mcp-tool'
        ? defaultBlockingMcpToolPrompt(args.durationMs)
        : defaultLongRunPrompt(args.durationMs, args.intervalMs))
  console.log(
    `Long-run probing ${String(toProbe.length)} agent(s): ${toProbe.map((t) => t.agent.id).join(', ')}`,
  )
  console.log(
    `Duration: ${String(args.durationMs)}ms; timeout: ${String(timeoutMs)}ms; mode: ${args.mode}; prompt: ${prompt.slice(0, 120)}${prompt.length > 120 ? '...' : ''}\n`,
  )

  const reports: AcpLongRunReport[] = []
  for (const { agent, path } of toProbe) {
    process.stdout.write(`  ${agent.title} ... `)
    if (path === null) {
      reports.push({
        agentId: agent.id,
        title: agent.title,
        command: agent.command,
        args: agent.args,
        prompt,
        mode: args.mode,
        ok: false,
        error: 'not installed (not on PATH)',
        elapsedMs: 0,
        expectedDurationMs: args.durationMs,
        completedEarly: true,
        firstUpdateAfterMs: null,
        lastUpdateAfterMs: null,
        maxSilentGapMs: null,
        updateCount: 0,
        updateKinds: [],
        textChunkCount: 0,
        toolCallCount: 0,
        fsReadRequestCount: 0,
        mcpToolCallCount: 0,
        mcpToolCompletedCount: 0,
        mcpToolClosedBeforeResultCount: 0,
        permissionRequests: [],
      })
      console.log('not installed')
      continue
    }
    const env = envFor(agent.envHints)
    const report = await probeAgentLongRun(
      {
        agentId: agent.id,
        title: agent.title,
        command: agent.command,
        args: agent.args,
        ...(env ? { env } : {}),
        cwd,
      },
      {
        durationMs: args.durationMs,
        progressIntervalMs: args.intervalMs,
        timeoutMs,
        mode: args.mode,
        prompt,
      },
    )
    reports.push(report)
    if (report.ok) {
      console.log(`ok (${fmtMs(report.elapsedMs)}, max gap ${fmtMs(report.maxSilentGapMs)})`)
    } else {
      console.log(`failed after ${fmtMs(report.elapsedMs)} (${report.error ?? 'unknown'})`)
    }
  }

  const meta = {
    probedAt: new Date().toISOString(),
    host: `${platform()} ${release()} (${hostname()})`,
  }
  const markdown = renderMarkdown(reports, meta)
  const json = { generatedBy: 'npm run probe:acp:long', ...meta, reports }
  console.log(`\n${markdown}`)

  if (args.write) {
    const mdPath = resolve(cwd, `${args.out}.md`)
    const jsonPath = resolve(cwd, `${args.out}.json`)
    await mkdir(dirname(mdPath), { recursive: true })
    await writeFile(mdPath, markdown, 'utf-8')
    await writeFile(jsonPath, `${JSON.stringify(json, null, 2)}\n`, 'utf-8')
    console.log(`Wrote ${args.out}.md and ${args.out}.json`)
  }
}

if (require.main === module) {
  main().catch((err: unknown) => {
    console.error(err)
    process.exit(1)
  })
}
