import assert from 'node:assert/strict'
import { execFileSync, spawnSync } from 'node:child_process'
import { chmod, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, describe, it } from 'node:test'
import { z } from 'zod'
import { decodeWithSchema, safeJsonParse } from '../src/shared/safe-json.ts'

const SCRIPT = resolve('assets/skills/reconcile-worktrees/scripts/audit-worktrees.mjs')

const auditArtifactSchema = z.object({
  ignored: z.boolean(),
  kind: z.string(),
  name: z.string(),
  size_bytes: z.number(),
  symlink_target: z.string().optional(),
})
const auditStatusSchema = z.object({
  dirty_entries: z.number(),
  porcelain: z.array(z.string()),
  staged_entries: z.number(),
  untracked_entries: z.number(),
  unstaged_entries: z.number(),
})
const auditComparisonSchema = z.object({
  patch_equivalent_commits: z.number(),
  unique_patch_commits: z.number(),
})
const auditResultSchema = z.object({
  artifact_bytes: z.number(),
  base: z.string(),
  dirty_worktree_count: z.number(),
  error_worktree_count: z.number(),
  worktree_count: z.number(),
  worktrees: z.array(
    z.object({
      artifact_bytes: z.number(),
      artifacts: z.array(auditArtifactSchema),
      branch: z.string().nullable(),
      comparison: auditComparisonSchema.optional(),
      current: z.boolean(),
      error: z.string().optional(),
      path: z.string(),
      status: auditStatusSchema.optional(),
    }),
  ),
})
type AuditResult = z.infer<typeof auditResultSchema>

const roots: string[] = []

function git(cwd: string, args: string[]): string {
  return execFileSync('git', args, {
    cwd,
    encoding: 'utf8',
    env: {
      ...process.env,
      GIT_AUTHOR_NAME: 'Copse Test',
      GIT_AUTHOR_EMAIL: 'copse@example.invalid',
      GIT_COMMITTER_NAME: 'Copse Test',
      GIT_COMMITTER_EMAIL: 'copse@example.invalid',
    },
  })
}

function audit(repo: string, args: string[] = []): AuditResult {
  const output = execFileSync(process.execPath, [SCRIPT, '--repo', repo, ...args], {
    encoding: 'utf8',
  })
  const parsed = safeJsonParse(output, decodeWithSchema(auditResultSchema))
  assert.ok(parsed, 'expected the audit helper to return its documented JSON shape')
  return parsed
}

async function fixture(): Promise<{ repo: string; worktree: string }> {
  const root = await mkdtemp(join(tmpdir(), 'reconcile-worktrees-skill-'))
  roots.push(root)
  const repo = join(root, 'repo with spaces')
  const worktree = join(root, 'feature worktree')
  await mkdir(repo, { recursive: true })
  git(repo, ['init', '-q', '-b', 'main'])
  await writeFile(join(repo, '.gitignore'), 'node_modules/\ndist/\n')
  await writeFile(join(repo, 'tracked.txt'), 'base\n')
  git(repo, ['add', '.'])
  git(repo, ['commit', '-q', '-m', 'base'])
  git(repo, ['branch', 'feature'])
  git(repo, ['worktree', 'add', '-q', worktree, 'feature'])
  await writeFile(join(worktree, 'tracked.txt'), 'feature\n')
  git(worktree, ['add', 'tracked.txt'])
  git(worktree, ['commit', '-q', '-m', 'feature'])
  git(repo, ['merge', '--squash', 'feature'])
  git(repo, ['commit', '-q', '-m', 'land feature'])
  return { repo, worktree }
}

afterEach(async () => {
  for (const root of roots.splice(0).reverse()) await rm(root, { recursive: true, force: true })
})

describe('built-in reconcile-worktrees audit', () => {
  it('auto-detects the base and recognizes a squash-equivalent dirty worktree', async () => {
    const { repo, worktree } = await fixture()
    await writeFile(join(worktree, 'scratch.txt'), 'unfinished\n')
    await mkdir(join(worktree, 'node_modules'), { recursive: true })
    await writeFile(join(worktree, 'node_modules', 'large.bin'), 'x'.repeat(4096))

    const result = audit(repo, ['--path', worktree])

    assert.equal(result.base, 'main')
    assert.equal(result.worktree_count, 1)
    assert.equal(result.dirty_worktree_count, 1)
    assert.equal(result.error_worktree_count, 0)
    const item = result.worktrees[0]
    assert.ok(item)
    assert.ok(item.status)
    assert.ok(item.comparison)
    assert.equal(item.current, false)
    assert.equal(item.branch, 'feature')
    assert.equal(item.status.dirty_entries, 1)
    assert.equal(item.status.untracked_entries, 1)
    assert.equal(item.comparison.patch_equivalent_commits, 1)
    assert.equal(item.comparison.unique_patch_commits, 0)
    assert.ok(item.artifact_bytes >= 4096)
    assert.deepEqual(
      item.artifacts.map(({ name, ignored, kind }) => ({ name, ignored, kind })),
      [{ name: 'node_modules', ignored: true, kind: 'directory' }],
    )
  })

  it('keeps ignored generated bytes separate from Git dirty status', async () => {
    const { repo, worktree } = await fixture()
    await mkdir(join(worktree, 'node_modules'), { recursive: true })
    await writeFile(join(worktree, 'node_modules', 'generated.bin'), 'x'.repeat(4096))

    const result = audit(repo, ['--path', worktree])
    const item = result.worktrees[0]

    assert.ok(item)
    assert.ok(item.status)
    assert.equal(result.dirty_worktree_count, 0)
    assert.equal(item.status.dirty_entries, 0)
    assert.ok(item.artifact_bytes >= 4096)
    const artifact = item.artifacts[0]
    assert.ok(artifact)
    assert.equal(artifact.ignored, true)
  })

  it('reports patch-equivalent and genuinely unique commits independently', async () => {
    const { repo, worktree } = await fixture()
    await writeFile(join(worktree, 'unique.txt'), 'not on main\n')
    git(worktree, ['add', 'unique.txt'])
    git(worktree, ['commit', '-q', '-m', 'unique follow-up'])

    const result = audit(repo, ['--path', worktree])
    const item = result.worktrees[0]

    assert.ok(item?.comparison)
    assert.equal(item.comparison.patch_equivalent_commits, 1)
    assert.equal(item.comparison.unique_patch_commits, 1)
  })

  it('keeps staged, unstaged, and untracked work distinct', async () => {
    const { repo, worktree } = await fixture()
    await writeFile(join(worktree, 'tracked.txt'), 'unstaged change\n')
    await writeFile(join(worktree, 'staged.txt'), 'staged change\n')
    git(worktree, ['add', 'staged.txt'])
    await writeFile(join(worktree, 'untracked file.txt'), 'untracked change\n')

    const result = audit(repo, ['--path', worktree])
    const item = result.worktrees[0]

    assert.ok(item?.status)
    assert.equal(item.status.dirty_entries, 3)
    assert.equal(item.status.staged_entries, 1)
    assert.equal(item.status.unstaged_entries, 1)
    assert.equal(item.status.untracked_entries, 1)
    assert.deepEqual(item.status.porcelain, [
      'A  staged.txt',
      ' M tracked.txt',
      '?? untracked file.txt',
    ])
  })

  it('prefers the configured remote default branch over a local main assumption', async () => {
    const { repo, worktree } = await fixture()
    git(repo, ['update-ref', 'refs/remotes/origin/trunk', 'refs/heads/main'])
    git(repo, ['symbolic-ref', 'refs/remotes/origin/HEAD', 'refs/remotes/origin/trunk'])

    const result = audit(repo, ['--path', worktree])

    assert.equal(result.base, 'refs/remotes/origin/trunk')
  })

  it('audits only explicitly requested custom artifact names', async () => {
    const { repo, worktree } = await fixture()
    await mkdir(join(worktree, 'node_modules'))
    await writeFile(join(worktree, 'node_modules', 'dependency.bin'), 'dependency\n')
    await mkdir(join(worktree, 'cache-output'))
    await writeFile(join(worktree, 'cache-output', 'cache.bin'), 'cache\n')

    const result = audit(repo, ['--path', worktree, '--artifact', 'cache-output'])

    assert.deepEqual(
      result.worktrees[0]?.artifacts.map(({ name, ignored }) => ({ name, ignored })),
      [{ name: 'cache-output', ignored: false }],
    )
  })

  it('reports an unignored dependency symlink without following its target', async () => {
    const { repo, worktree } = await fixture()
    const target = join(repo, 'shared-dependencies')
    await mkdir(target)
    await writeFile(join(target, 'keep.bin'), 'x'.repeat(1024 * 1024))
    await writeFile(join(worktree, '.gitignore'), 'dist/\n')
    await symlink(target, join(worktree, 'node_modules'))

    const result = audit(repo, ['--path', worktree])
    const artifact = result.worktrees[0]?.artifacts[0]

    assert.ok(artifact)
    assert.equal(artifact.name, 'node_modules')
    assert.equal(artifact.kind, 'symlink')
    assert.equal(artifact.ignored, false)
    assert.equal(artifact.symlink_target, target)
    assert.ok(
      artifact.size_bytes < 64 * 1024,
      'the audit must size the link, not its 1 MiB target tree',
    )
  })

  it('reports a missing registered worktree instead of aborting the whole audit', async () => {
    const { repo, worktree } = await fixture()
    await rm(worktree, { recursive: true, force: true })

    const result = audit(repo)
    const missing = result.worktrees.find((item) => item.error)

    assert.equal(result.error_worktree_count, 1)
    assert.match(missing?.error ?? '', /registered worktree path is missing/)
  })

  it('rejects artifact paths that could escape a worktree', async () => {
    const { repo } = await fixture()
    const result = spawnSync(
      process.execPath,
      [SCRIPT, '--repo', repo, '--artifact', '../outside'],
      { encoding: 'utf8' },
    )

    assert.equal(result.status, 2)
    assert.match(result.stderr, /one top-level name/)
  })

  it('rejects the Git metadata directory as an artifact target', async () => {
    const { repo } = await fixture()
    const result = spawnSync(process.execPath, [SCRIPT, '--repo', repo, '--artifact', '.git'], {
      encoding: 'utf8',
    })

    assert.equal(result.status, 2)
    assert.match(result.stderr, /one top-level name/)
  })

  it('rejects paths that are not exact registered worktrees', async () => {
    const { repo } = await fixture()
    const result = spawnSync(
      process.execPath,
      [SCRIPT, '--repo', repo, '--path', join(repo, 'not-a-worktree')],
      { encoding: 'utf8' },
    )

    assert.equal(result.status, 2)
    assert.match(result.stderr, /not registered worktrees/)
  })

  it('ships as an executable resource copied with the built-in skill', async () => {
    await chmod(SCRIPT, 0o755)
    const result = spawnSync(SCRIPT, ['--help'], { encoding: 'utf8' })
    assert.equal(result.status, 0)
    assert.match(result.stdout, /Read-only JSON audit/)
  })

  it('keeps destructive cleanup behind explicit safety guardrails', async () => {
    const instructions = await readFile(
      resolve('assets/skills/reconcile-worktrees/SKILL.md'),
      'utf8',
    )

    assert.match(instructions, /Never use `git clean -fdX`/)
    assert.match(instructions, /explicit confirmation before `git worktree remove --force`/)
    assert.match(instructions, /Preserve local branches by default/)
    assert.match(instructions, /Never remove the primary checkout, current checkout/)
    assert.match(instructions, /Do not claim closure.*without post-action verification/)
  })
})
