#!/usr/bin/env bash
# Run the unit tests in servo's `components/layout/svg/` without building Servo.
#
# Why this exists: `cargo test -p servo-layout` cannot be run in this stack.
# From `tauri-shell/` servo-layout is a path dependency and not a workspace
# member, so cargo refuses to test it; and servo's own workspace cannot be
# built here at all (it resolves a different mozjs_sys than the one tauri-shell
# has already compiled, and that build fails at linker detection). The layout
# SVG code is deliberately written so its geometry is pure — depending only on
# euclid and one pref lookup — which makes it testable in a throwaway crate
# that #[path]-includes the real files. No source is duplicated: the files are
# copied verbatim on every run, so a test can never drift from the code.
#
# Usage: scripts/servo-svg-unit-tests.sh [test-filter]
#   SERVO_DIR   servo checkout (default: <repo>/../servo)
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
servo_dir="${SERVO_DIR:-$repo_root/../servo}"
svg_dir="$servo_dir/components/layout/svg"

if [[ ! -d "$svg_dir" ]]; then
  echo "no such directory: $svg_dir" >&2
  echo "set SERVO_DIR to a servo checkout carrying the native-SVG patches" >&2
  exit 1
fi

harness="${TMPDIR:-/tmp}/servo-layout-svg-tests"
rm -rf "$harness"
mkdir -p "$harness/src"

cat > "$harness/Cargo.toml" <<'TOML'
# Generated by scripts/servo-svg-unit-tests.sh — do not edit.
[workspace]
[package]
name = "servo-layout-svg-tests"
version = "0.0.0"
edition = "2024"          # servo uses let-chains
publish = false

[dependencies]
euclid = "0.22"
kurbo = "0.13.1"
vello_cpu = { version = "0.0.9", features = ["multithreading"] }
TOML

# `servo_config::pref!` is the module's only dependency on the rest of Servo.
# Stub it as `false`: the geometry under test does not consult it, and the one
# function that does is asserted against the stubbed value.
cat > "$harness/src/lib.rs" <<'RUST'
// `macro_rules!` is textually scoped, so declaring it before the module makes
// `pref!` resolve inside it without an import.
macro_rules! pref {
    ($name:ident) => {
        false
    };
}
pub mod svg;
RUST

cp -R "$svg_dir" "$harness/src/svg"
sed -i.bak '/^use servo_config::pref;$/d' "$harness/src/svg/mod.rs"

# `svg/number.rs` in-tree only re-exports the parser, which lives in
# layout_api so `SVGElementData::ratio_from_view_box` can share it. Substitute
# the real source so the harness tests the same code, not a stub.
sed -e 's/^pub struct NumberListParser/pub(crate) struct NumberListParser/' \
    -e 's/^    pub fn /    pub(crate) fn /' \
    "$servo_dir/components/shared/layout/svg_number.rs" > "$harness/src/svg/number.rs"

# Two modules bridge to stylo and the DOM and cannot build standalone. They
# are deliberately thin for exactly this reason: everything with real edge
# cases lives in the pure modules, which is what gets tested here. If this
# list has to grow, that is a signal logic has leaked into the bridge.
for coupled in foreign image integration pservers resolve text tree; do
  rm -f "$harness/src/svg/$coupled.rs"
  sed -i.bak "/^pub(crate) mod $coupled;$/d" "$harness/src/svg/mod.rs"
done
rm -f "$harness/src/svg/mod.rs.bak"

cd "$harness"
exec cargo test --quiet -- --nocapture "$@"
